### ISSUE TITLE
Allow users to change scientific notation to other format

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lixun910/geoda#151]
```
Add preference option to allow users to change the formatting of scientific 
notation.

Discussion:

Short answer:  I haven’t provided this an an option
in the program yet.  It defaults to scientific notation
for longer numbers.

Longer answer:
It would not be too difficult to provide an option to
change number formatting.  However, there are a
few questions/complications with doing so:

1) Does the preference affect just the current view?
2) Does the preference affect all views of that type?
3) Should the preference be program wide?
4) Should the preference be saved with the project file?
5) Should the preference be saved in some sort of
  new preference file for the user and if so where
  will that file be stored?

I have long wanted to provide more preferences
for users, but when there are more preferences the
need to store them permanently somehow would
be needed.
```

Original issue reported on code.google.com by `jkosc...@asu.edu` on 16 Oct 2014 at 2:01

**Comment by lixun910** [comment]
This is marked as for "future", but that might be an simple version of this issue: allow user to select "scientific notation" or not for all plots. Julia, let me know if you want to get this simple feature done, so I can create  a new issue.

**Comment by jkoschinsky** [comment]
I have another open ticket for this but user choice would be better if it's
quick, so yes, that would be great to add. Thx!

On Thursday, 13 August 2015, Xun Li <notifications@github.com> wrote:
> This is marked as for "future", but that might be an simple version of
this issue: allow user to select "scientific notation" or not for all
plots. Julia, let me know if you want to get this simple feature done, so I
can create a new issue.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/tWgCbQX8oNDCcEmd7PgRNdVhnxWJlGyJ9UbOXz00KPD43WEmEY2RaOUYbjewYofM4BLZxjUCpqh17Lht7-TnTe42m97WoCp9q7UwbAWBKAt5eAxfMtlikoPkeszswUYOqrGa6yGspTJ2QVcWPOUkf4kl_Thjbw=s0-d-e1-ft#https://github.com/notifications/beacon/ANC8f_A4VXoFzMGX3kckUxZWegmuH22Rks5onTm5gaJpZM4FrXQr.gif
>

-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.63
