### ISSUE TITLE
Basemap: GeoDa crashes after open/close several maps using basemap

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lixun910/geoda#186]
```
Basemap: GeoDa crashes after open/close several maps using basemap
```

Original issue reported on code.google.com by `lixun...@gmail.com` on 30 Jun 2015 at 7:31

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.63 - couldn't get it to crash with multiple maps that had varies types of basemaps enabled.
