### ISSUE TITLE
Suggested selection dialog redesign

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#210]
Here's how I would suggest redesigning the selection dialog. We can discuss on Monday.

![selection dialog redesign](https://cloud.githubusercontent.com/assets/13679743/9506881/7e9247de-4bff-11e5-9c3d-9a3be7162e1a.png)

**Comment by jkoschinsky** [comment]
Updated selection dialog redesign that includes Luc's and Xun's feedback
![selection2](https://cloud.githubusercontent.com/assets/13679743/9532227/28d275ec-4cbf-11e5-9c71-5ac2461fa35b.png)

**Comment by lixun910** [comment]
This design is still not correct when comes to "Edit selection"---- Suppose you already have "south" of NAT selected. To "Edit selection" (e.g.  from "south", select "population" in range x1 to x2), you still need the items  in "New selection" category.

My suggestion is keep the original "selection", and add one more radio button:  
O New selection O select from current selection O append to current selection

Then, remove random selection.

**Comment by jkoschinsky** [comment]
Let's discuss tomorrow - the original design is too confusing because there
is no structure in the buttons.

On 30 August 2015 at 11:35, Xun Li <notifications@github.com> wrote:

> This design is still not correct when comes to "Edit selection"----
> Suppose you already have "south" of NAT selected. To "Edit selection" (e.g.
> from "south", select "population" in range x1 to x2), you still need the
> items in "New selection" category.
>
> My suggestion is keep the original "selection", and add one more radio
> button:
>
> O New selection O select from current selection O append to current
> selection
>
> Then, remove random selection.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/210#issuecomment-136174034>.
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by jkoschinsky** [comment]
One option could be to also display the "select all in range" option from new selection in the edit selection (below select from / append to).

**Comment by lixun910** [comment]
![screen shot 2015-08-30 at 12 55 44 pm](https://cloud.githubusercontent.com/assets/2423887/9569153/7c3bc950-4f16-11e5-9b9b-674c066b2671.png)
Let me know if this is more structural.

**Comment by jkoschinsky** [comment]
yes, thx, I like this - let's remove the lines between clear-invert-add neighbors and remove random selection altogether. And let's move "select all undefined" in the middle group.

And let's change the order to undefined, then invert, then neighbors, then clear.

thx!

**Comment by lixun910** [comment]
why remove random selection? I think it's a pretty neat function for people wants simple random observations?

**Comment by jkoschinsky** [comment]
Luc wanted it out because people don't use it

**Comment by jkoschinsky** [comment]
see other ticket: If you select observations in table or map and add a variable in the Selection Tool (e.g. with 1 for selected and 0 for unselected), then the Apply button isn't enabled but it should be.

**Comment by lixun910** [comment]
fixed in ci 818627797b0b511eae43bf69741fe93ce4098cd3
see issue #221

**Comment by jkoschinsky** [comment]
see ticket 347
Otherwise verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
