### ISSUE TITLE
Suggested Redesign of Category Editor Dialog

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#215]
This only involves rearranging the GUI components, no backend changes.

![category editor](https://cloud.githubusercontent.com/assets/13679743/9535310/ef347144-4cd4-11e5-8181-ec587f9671a8.png)

**Comment by lixun910** [comment]
Update the UI by removing box but adding Label for each "input group".

Also, adjust the labels of the sliderbar -- current labels are overlayed on sliderbar

**Comment by lixun910** [comment]
Remove the "uni. dist. Min." inputs for changing the MIN/MAX labels/values for the sliderbar.

**Comment by jkoschinsky** [comment]
The 0-1 slider bar is much longer than the legend categories. I think we made it long to have more precision in the break values but the current design looks weird. Can we either make the 0-1 slider bar shorter so it aligns with the length of the legend categories or space out the legend categories so they match the length of the slider bar?

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
