### ISSUE TITLE
Average Charts: add space-time dummies for DID tests

### ISSUE THREAD

**Issue by lixun910** [lixun910/geoda#216]
For regimes and times, add dummy variables in a virtual table. Then run a regression.

**Comment by jkoschinsky** [comment]
To access this, when user right-clicks on view, instead of "Save Dummies" add "Run Diff-inDiff".
Then run the regression and open a regression view (same formatting/style as for regular regression).

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
