### ISSUE TITLE
Grid Export/Saving not working

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#233]
from Luc:

- I create a grid from scratch using Tools > Shape > Polygon from grid and save (export)
  the shape file
- I read the shape file back in
  - the right click on the table does not work to invoke the options, but the menu works (on top)
  - I add a new variable, e.g., a standard normal variable
- I try to save the new data, but get the “read only” error, use “export” - this is the same error
  as before, there should not be any “read only” files created.

- As an aside, the grid creation dialog should have an option to ignore the lower left and upper
  right coordinates and just set the number of rows and columns, the bounding box can then be
  set arbitrarily to 0,0 1,1. As it is, it’s pretty annoying to have to enter bounding box coordinates
  when all you want is a grid.

**Comment by lixun910** [comment]
to avoid enter bounding box coodrinates, the default value of input boxes (upper top, upper right) are set to 1.0. This is an easy solution.

**Comment by jkoschinsky** [comment]
Confirmed for 1.7.63.

only small typo: Gird Size --> Grid Size

Once small typo is fixed, this ticket can be closed.

**Comment by jkoschinsky** [comment]
waiting for next release

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.87 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
