### ISSUE TITLE
make db information persistent in dialog

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#237]
It would be nice if the information on the database host, port,
etc. would remain in the dialog. Right now, in the use case that
one wants to look at multiple tables from the same data base,
all this information needs to be re-entered through New Project>
Database. That way, one would only have to change the table
name, or change the database on the same server.
The less one has to retype, the better.

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.87 (OSX Yosemite, 10.10.5).
