### ISSUE TITLE
Correlogram help text

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#238]
3 small typos to correct:

parition --> partition
observations centers are apart --> observation centers are apart
10000 --> 10,000

**Comment by jkoschinsky** [comment]
Text fix verified.

One other issue:
Right now the help window is locked as long as the correlogram parameter window is open:

<img width="682" alt="screen shot 2016-03-02 at 9 15 20 pm" src="https://cloud.githubusercontent.com/assets/13679743/13484522/f3214cfc-e0bb-11e5-8cdd-fb2cce842138.png">

This means that e.g. you can't read the help text at the bottom/on "random sample" without first running the correlogram (which can take long for very large datasets where the random sample is relevant). Let's make the full help text accessible before hitting Apply (if scrolling doesn't work, let's decrease the font size/formatting so the whole text is visible in the default size of the help window).

**Comment by lixun910** [comment]
Please verify in 1.7.89

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.89 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
