### ISSUE TITLE
Replace "Choose Weights" message

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#239]
Right now some of the "choose weights" views says "no weights found - use weights manager" (e.g. for weights histogram). Let's replace this with the attached weights message, which is friendlier and explains where to find the weights manager.

**Comment by jkoschinsky** [comment]
![screen shot 2015-11-01 at 9 35 47 am](https://cloud.githubusercontent.com/assets/13679743/10891359/854483fc-816b-11e5-8608-4b5a19c6b1d8.png)

**Comment by jkoschinsky** [comment]
Meanwhile we changed the weights warning to this if you could update throughout:

GeoDa could not find the required weights file.
Please specify weights in Tools > Weights Manager.

**Comment by lixun910** [comment]
Please verify in 1.7.87

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.87 (OSX Yosemite, 10.10.5).
