### ISSUE TITLE
Disable time dropdown in variable selection if no variables are grouped

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#240]
In "Variable Settings" (maps, scatterplot, box plot etc.), the time option is displayed even when there are no grouped variables. This is confusing since changing the time periods doesn't actually change anything. Can we only enable this option in case there are grouped variables in the table?

**Comment by lixun910** [comment]
what's "Variable Settings"? can you post a screenshot? thanks!

**Comment by jkoschinsky** [comment]
![screen shot 2015-11-11 at 2 08 11 pm](https://cloud.githubusercontent.com/assets/13679743/11100189/baa5607a-887d-11e5-93a8-f347cb22539e.png)

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
