### ISSUE TITLE
Time menus

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#242]
One expert GeoDa user I recently talked to at length thought that there are currently too many table right-click options. I agree.

I would remove animation and time control, which is really about views, not the table, as well as the category editor. And change the name and order of Variable Grouping Editor and Time Editor to "Group Variables" and "Group Selected" so the table list looks like this:

--Group Variables
--Group Selected
--Ungroup
--Edit Groups

On the main menu, I would add a new menu item "Time", e.g. between map and explore with the following time options:
--Animation
--Time Control
--Group Variables
--Edit Groups

The time control would also link to Group Variables as described in another ticket.

**Comment by jkoschinsky** [comment]
Verified except:
Remove category editor from table right-click options.

**Comment by lixun910** [comment]
Please verify in 1.7.87

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.87 (OSX Yosemite, 10.10.5).
