### ISSUE TITLE
Table: update "Points from Table" labeling

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#246]
I'm getting questions about whether X or Y is lat/long. Let's edit the label:

1st Variable (X or Long)
2nd Variable (Y or Lat)

**Comment by jkoschinsky** [comment]
Latitue --> Latitude

<img width="396" alt="screen shot 2016-03-02 at 10 39 34 pm" src="https://cloud.githubusercontent.com/assets/13679743/13485702/bbf4c770-e0c7-11e5-96ce-ac50db02fe73.png">

**Comment by lixun910** [comment]
Latitue

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.87 (OSX Yosemite, 10.10.5).
