### ISSUE TITLE
Weights: contiguity weights for points

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#248]
When you open the weights creation dialog for points, the contiguity weights options (queen and rook) are enabled. GeoDa used to convert points to Thiessen polygons on the backend and then create the contiguity weights (like in GeoDaSpace).

However, when you try to do the same thing now (e.g. with baltimore shapefile), you get this error message:

![screen shot 2015-11-11 at 11 57 57 am](https://cloud.githubusercontent.com/assets/13679743/11097119/804c5602-886b-11e5-8ff2-f06f67e3c5de.png)

**Comment by jkoschinsky** [comment]
Worked in Windows for baltimore sample data (queen weights) but afterwards when you clicked on "create weights" nothing happened. In Mac OSX, it didn't work and generated this error message (tired both rook and queen):

<img width="605" alt="screen shot 2016-03-02 at 10 53 56 pm" src="https://cloud.githubusercontent.com/assets/13679743/13485938/b425f224-e0c9-11e5-9aae-8c3505b9cd47.png">

**Comment by lixun910** [comment]
I doubt it's the international path issue? since I have it work on my side.

**Comment by jkoschinsky** [comment]
ok, i just put balt.shp on desktop and it does work now, so it must be
related to the path, you're right.

But the path where it didn't work was this, with no international
characters.

/Users/Julia/Julia/GeoDa\ Center/Data/Baltimore/baltimore/baltim.shp

What's the difference?

On 2 March 2016 at 22:59, Xun Li <notifications@github.com> wrote:

> I doubt it's the international path issue? since I have it work on my side.
>
>
> On Wed, Mar 2, 2016 at 10:56 PM, jkoschinsky <notifications@github.com>
> wrote:
>
> > Worked in Windows for baltimore sample data (queen weights) but
> afterwards
> > when you clicked on "create weights" nothing happened. In Mac OSX, it
> > didn't work and generated this error message (tired both rook and queen):
> >
> > [image: screen shot 2016-03-02 at 10 53 56 pm]
> > <
> https://cloud.githubusercontent.com/assets/13679743/13485938/b425f224-e0c9-11e5-9aae-8c3505b9cd47.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/lixun910/geoda/issues/248#issuecomment-191595058>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/248#issuecomment-191595678>.
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by lixun910** [comment]
I can see the space in the path. I will check the save weights code, since
it's from an old piece of code.

Xun Li, Ph.D

Research Scientist
GeoDa Center for Geospatial Analysis and Computation
School of Geographical Sciences and Urban Planning
Arizona State University
http://www.public.asu.edu/~xunli/cv.html

**Comment by lixun910** [comment]
I've tested on my side: the space in the path works; the international  characters in the path works as well.

From your path, /Users/Julia/Julia/..., I guess you copied the directory "Julia" from another HD? if it is, there might be a permission (of writing) issue, which might cause the GeoDa failed to write a weights file to the path you specified. 

Can you view the location using Finder to see if there's a icon like this?
![image](https://cloud.githubusercontent.com/assets/2423887/13503608/85df0d7e-e12d-11e5-8eba-4229c6cce522.png)

**Comment by jkoschinsky** [comment]
Yes, you're right, for some weird reason the folder was locked. Once I unlocked it, both contiguity and distance weights work, so I'll close this.
