### ISSUE TITLE
Table menu

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#249]
In the table menu, let's replace "Invert Selection" with "Add Neighbors to Selection" since the latter is more frequently used than the former and it's a feature we want to highlight.

**Comment by lanselin** [comment]
I don’t agree. While I agree that add neighbors to selection is a GeoDa-specific feature,
inverting the selection is a standard operation. I personally use/need it a lot.
Let’s be very careful before we remove features. We can move them to a different place,
but I would be very wary of removing current functionality (if only to keep backward
compatibility)


--  
Luc Anselin, PhD
Regents' Professor and Walter Isard Chair
Director, GeoDa Center for Geospatial Analysis and Computation
School of Geographical Sciences and Urban Planning
Arizona State University

**Comment by jkoschinsky** [comment]
Hi Luc,

This is definitely not about removing the invert selection option, which I
also use, but only about the location of where this is accessed. See
attached screenshot of selection tool where invert selection is included.
My suggestion was to only replace the right-click menu option from invert
to add neighbors so people have the shortcut to it. This came up in the
demos here where people wanted to add the neighbors and could find the
feature anymore (we used to have it as a right-click option and took it out
bc the list was getting too long). If you prefer to leave it in the
right-click, we could add neighbors and leave invert selection, so we have
both. Julia


[image: Inline images 1]

On 11 November 2015 at 13:43, Luc Anselin <notifications@github.com> wrote:

> I don’t agree. While I agree that add neighbors to selection is a
> GeoDa-specific feature,
> inverting the selection is a standard operation. I personally use/need it
> a lot.
> Let’s be very careful before we remove features. We can move them to a
> different place,
> but I would be very wary of removing current functionality (if only to
> keep backward
> compatibility)
>
>
> --
> Luc Anselin, PhD
> Regents' Professor and Walter Isard Chair
> Director, GeoDa Center for Geospatial Analysis and Computation
> School of Geographical Sciences and Urban Planning
> Arizona State University
>
>
> On Wednesday, November 11, 2015 at 10:31 AM, jkoschinsky wrote:
>
> > In the table menu, let's replace "Invert Selection" with "Add Neighbors
> to Selection" since the latter is more frequently used than the former and
> it's a feature we want to highlight.
> >
> > —
> > Reply to this email directly or view it on GitHub (
> https://github.com/lixun910/geoda/issues/249).
> >
> >
> >
> >
> >
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/249#issuecomment-155873143>.
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by lanselin** [comment]
OK, let’s have them both as right click.

--  
Luc Anselin, PhD
Regents' Professor and Walter Isard Chair
Director, GeoDa Center for Geospatial Analysis and Computation
School of Geographical Sciences and Urban Planning
Arizona State University

**Comment by lixun910** [comment]
I don't think we have this logic in the right click menu before.  I will add this new menu item, but need to add a logic like: if user doesn't have a weights yet, then prompt them to select/define a weights. Or, if they have more than one weights defined, prompt a select box?

**Comment by lanselin** [comment]
I would suggest the same logic as whenever a weights file is needed.
If one has been specified, the “last one” is used. If none is specified,
the user gets the usual prompt to create or read the weights.
This maintains consistency with the other weights operations.

--  
Luc Anselin, PhD
Regents' Professor and Walter Isard Chair
Director, GeoDa Center for Geospatial Analysis and Computation
School of Geographical Sciences and Urban Planning
Arizona State University

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
