### ISSUE TITLE
Category Editor interface

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#256]
Let’s go back to listing the minimum on top of the slider and the max at the bottom like we used to have since it’s otherwise hard to tell what these two numbers mean.

* take out:
  * line above “define custom breaks” and “define custom breaks header” so there’s just two categories: 
“create custom breaks” and edit custom breaks
  * preview var option below histogram preview and keep “same as assoc var as default”

* move “assoc. var” and the variable selection to its right above “Breaks”
* change default setting to user-defined, quantile, 4 categories

* sometimes when you first open the Category Editor with the default of user defined categories, the slider is gone

* right-click/options for maps, cartograms and bubble charts, PCP, Conditional Map:
  * Create New Custom and list names of the new categories you created but remove other custom breaks from list

* The cartogram contains a “Save Categories” option. Let’s add this as a button at the bottom of the category editor. This option is disabled for user defined categories.

**Comment by jkoschinsky** [comment]
These two changes aren't implemented yet:

- change default setting to user-defined, quantile, 4 categories (current default is quantile)

- The cartogram contains a “Save Categories” option. Let’s add this as a button at the bottom of the category editor. This option is disabled for user defined categories.

Let's discuss tomorrow if we want these for 1.8 or later.

**Comment by lixun910** [comment]
crash: when create a new "custom category" in histogram, close it. Then, open "Category Editor" again, select just created "custom category". It will crash.

**Comment by jkoschinsky** [comment]
default settings fine with quantile

The cartogram contains a “Save Categories” option. Let’s add this as a button at the bottom of the category editor. This option is disabled for user defined categories.

**Comment by lixun910** [comment]
The crash has been fixed. You can verify it using 1.7.89

**Comment by lixun910** [comment]
please verify in 1.7.91

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.91 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
