### ISSUE TITLE
UI: Drag GeoDa App into App Folder

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#258]
IMO, there are too many files and too much text in the current install view that asks users to drag the GeoDa App into the general App folder. Most people won't read this and will just get confused. I suggest just showing the GeoDa icon, an arrow and the App icon, similar to what Chrome is doing:

<img width="629" alt="geoda" src="https://cloud.githubusercontent.com/assets/13679743/11329247/e9cdf9ca-9156-11e5-8dd5-03d1c16a8a78.png">

<img width="476" alt="chrome" src="https://cloud.githubusercontent.com/assets/13679743/11329250/f3a5d972-9156-11e5-8ec1-14c08e5aed7e.png">

**Comment by lixun910** [comment]
![screen shot 2016-02-15 at 9 39 15 pm](https://cloud.githubusercontent.com/assets/2423887/13067381/9e5fbe88-d42c-11e5-9d7f-2b13e8ed5985.png)

**Comment by lixun910** [comment]
![screen shot 2016-02-17 at 12 51 59 pm](https://cloud.githubusercontent.com/assets/2423887/13122652/4c3d4cf2-d575-11e5-9d8c-1d3990261935.png)

Here is the new installer design.

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).

looks great
