### ISSUE TITLE
Reorganize menu and toolbar

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#262]
Create a new menu and toolbar: 

<img width="1165" alt="screen shot 2015-11-22 at 9 11 09 pm" src="https://cloud.githubusercontent.com/assets/13679743/11329732/bf69f574-915d-11e5-893b-723d07e10f36.png">

Menu:
File - Edit - Tools - Table - Map - Explore - Space - Time - Regress - Options - Help

Edit:
--Time
--Categories

* rename Animation --> Map Movie
* make toolbar and icons larger (should work on 800x600 as min resolution)

**Comment by jkoschinsky** [comment]
Map menu and tooltip:

rename Animation --> Map Movie

**Comment by lixun910** [comment]
Please verify in 1.7.87

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.87 (OSX Yosemite, 10.10.5).
