### ISSUE TITLE
Crowdsource new toolbar icons

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#263]
As soon as we have new toolbar, crowdsource more modern version of icons (e.g. 99designs.com).
Explain groups and what tools do.

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
