### ISSUE TITLE
Scatterplot options

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#268]
Scatterplot options (for regular bivariate, and partly for scatter plot matrix, Moran scatterplot, and bubble chart):

* remove regimes regression as option when LOWESS is selected (since LOWESS is already regression on subsets)
* edit LOWESS Parameters - change default value for bandwidth from 0.70 to 0.20

Scatterplot options/right-click drop-down:

Data:
—Original (default)
—Standardized

Smoother:
—Linear (default)
—LOWESS

Show:
—Regimes Regression (default)
—Statistics (default)
—Axes Through Origin (default)
—Status Bar (default)

**Comment by jkoschinsky** [comment]
first point from ticket:

remove regimes regression as option when LOWESS is selected (since LOWESS is already regression on subsets)

not implemented yet

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
Update this text:
<img width="408" alt="screen shot 2016-03-05 at 11 57 41 am" src="https://cloud.githubusercontent.com/assets/13679743/13549731/9352c200-e2c9-11e5-986d-1ac20c32b563.png">

to:
View -->
Regimes Regression
Statistics
Axes Through Origin
Status Bar

Note: When you first select a subset of observations in another view, then LOWESS is disabled. However, when you first select LOWESS and then select observations in another view, you still get LOWESS with regimes. But as soon as you make a selection, LOWESS is disabled. We probably want to leave it like this, otherwise you'd have to disable selection but FYI that this is one way you can still get LOWESS with regimes.

**Comment by lixun910** [comment]
please verify in 1.7.91

**Comment by lixun910** [comment]
please verify in 1.7.91

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.91 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
