### ISSUE TITLE
Table - Edit Variable Properties

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#271]
Table - Edit Variable Properties:
* right-click on type to transform variable type, e.g. from integer to string or real to integer
* this would replace the current separate transformation dialog (Change Variable Type)
* remove rename from table right-click/options since this can be access through "Edit Variable Properties"

**Comment by lixun910** [comment]
![screen shot 2015-12-29 at 12 31 23 pm](https://cloud.githubusercontent.com/assets/2423887/12040647/17ad76a2-ae28-11e5-8ec6-defe6dec790e.png)

Directly change field type in Variable Properties dialog.
For database-type datasource, this "change type" process will lead the "type changed" field to be positioned at the end of the table.

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
