### ISSUE TITLE
Redesign UI for Variable Grouping Editor

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#272]
* Variable Grouping Editor --> Time Editor
* Time Control --> Time Player
* Clock Icon: when you select this, it opens both the Time Editor and the Time Player

* deactivate Time Editor until you have grouped variables
* double-click variables in Time Editor: edit time labels (instead of using double-click for left transfer as we currently do)
* remove placeholder and replace it by edit (to change labels for time periods)
* add save button for exporting the space-time table
* remove option to right-click on table to open variable grouping editor - instead, access it through the time player
* remove from right-click on table: “group selecte”d and “group unselected"

**Comment by lixun910** [comment]
![screen shot 2015-12-29 at 12 30 35 pm](https://cloud.githubusercontent.com/assets/2423887/12040634/fc3f21b8-ae27-11e5-9fee-170664665168.png)

**Comment by jkoschinsky** [comment]
sorry, this wasn't clear before: deactivate Time Player until you have grouped variables. Right now you can run the Time Player without having groups, so it runs but nothing changes.

Other changes are verified.

**Comment by lixun910** [comment]
This should be addressed in the fix of issue #345

**Comment by lixun910** [comment]
Please verify in 1.7.87

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.87 (OSX Yosemite, 10.10.5).
