### ISSUE TITLE
Export space-time table

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#273]
* allow users to export stacked space-time table as dbf, csv ... (see gdal options)
* for any grouped time variables
* what we currently only save in memory

for later:
* the project file recognizes time table so you don't have to recompute on the fly every time

![space-time table design and did](https://cloud.githubusercontent.com/assets/13679743/11357083/34d2748a-9221-11e5-850b-80ba85fd6b5e.jpg)

**Comment by lixun910** [comment]
fixe: truncated filename in gal/gwt weights file.

**Comment by jkoschinsky** [comment]
Right now the exported space-time table contains a new ID (STID), the time ID and the grouped variables:

![spacetime file](https://cloud.githubusercontent.com/assets/13679743/13477220/94e93ed4-e088-11e5-88a9-5921c14d1a75.png)

What we still need in addition is the spatial ID from the original table (see first column in photo above) that allows users to link the space-time file back to their original table.

**Comment by jkoschinsky** [comment]
ok, Xun just explained this: We're using the ID specification in the weights creation to also specify the spatial ID for the space-time table. If no weights are specified, then no spatial ID is added. Will update the GUI in the other ticket and close this one.
