### ISSUE TITLE
space-time weights

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#274]
space-time weights:
* stacking weights: new IDs
* copy-paste gal file for each time period with different IDs for the subsequent time periods

![space-time weights design and did](https://cloud.githubusercontent.com/assets/13679743/11357120/9bad0ea4-9221-11e5-81ed-cc49a9970fcb.jpg)

**Comment by jkoschinsky** [comment]
To get both a spatial ID in the space-time table and space-time weights, you need to have a weights file specified (if more than one weights are loaded, the active one seems to be used). Without that, you get the output above without spatial ID. Since this is pretty hidden right now, let's change the name of the save button:

Save As Space Time Table ... -->  Save Space-Time Table/Weights

Add this text at the end of the ? text for grouped variables:
Once you have grouped variables, you can save a new space-time table and weights: To add a spatial ID to your space-time table and create space-time weights, you need to have an active weights file (Tools-Weights Manager).

**Comment by lixun910** [comment]
Please verify in 1.7.87

**Comment by jkoschinsky** [comment]
GeoDa 1.7.87 (OSX Yosemite, 10.10.5).

I can't get a help window to open when clicking on this ?

<img width="249" alt="screen shot 2016-03-03 at 5 50 56 pm" src="https://cloud.githubusercontent.com/assets/13679743/13514718/944789f0-e168-11e5-882c-835e4bb0e970.png">

**Comment by lixun910** [comment]
Please verify in 1.7.89

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.89.
