### ISSUE TITLE
Histogram Options

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#275]
right-click/option for histogram:
* Move "Time Variable Options" to the bottom of the first block
* new first item on the right-click/options menu: Histogram Classification
  ** this has another drop-down: "Create New Custom" (opens Category Editor)
  ** if you created new categories, also list the names of new categories you created (same as for map)

Same thing for Conditional Histograms.

**Comment by lixun910** [comment]
For the feature: add "Create New Custom" for histogram. Here is an implementation (see below). However, here is my concern: 

in Histogram, the bins (intervals) must be adjacent, and are usually equal size (so does in the Histogram code). However, in "Category Editor", the intervals are not equal size (see the figure below (e.g. 0.99~1.66  < > 1.66~3.81). Even though, the "histogram" like figure on the right side uses "equal" size, which I think is wrong when interpret the x-axis. So, maybe not adding "Create New Custom" into Histogram menu?
![screen shot 2016-01-06 at 11 04 29 pm](https://cloud.githubusercontent.com/assets/2423887/12163413/a2c410fe-b4ca-11e5-909a-789fe9572535.png)

**Comment by lanselin** [comment]
The equal bin histogram is only one of many options. The custom classification allows one
to move beyond that to assess the effect of changing the bin sizes on the relative frequencies.
So, it’s OK to have it custom, as long as the bars reflect the new sizes, i.e., they should not
be equal size on the graph, but be proportional to the sizes suggested by the custom classification
(e.g., natural breaks).

**Comment by jkoschinsky** [comment]
It looks like we should also update this in the histogram view of the
category editor where the histogram bins are equal size even if the
interval sizes aren't.

On 7 January 2016 at 08:04, Luc Anselin <notifications@github.com> wrote:

> The equal bin histogram is only one of many options. The custom
> classification allows one
> to move beyond that to assess the effect of changing the bin sizes on the
> relative frequencies.
> So, it’s OK to have it custom, as long as the bars reflect the new sizes,
> i.e., they should not
> be equal size on the graph, but be proportional to the sizes suggested by
> the custom classification
> (e.g., natural breaks).
>
> > On Jan 7, 2016, at 12:10 AM, Xun Li <notifications@github.com> wrote:
> >
> > For the feature: add "Create New Custom" for histogram. Here is an
> implementation (see below). However, here is my concern:
> >
> > in Histogram, the bins (intervals) must be adjacent, and are usually
> equal size (so does in the Histogram code). However, in "Category Editor",
> the intervals are not equal size (see the figure below (e.g. 0.99~1.66 < >
> 1.66~3.81). Even though, the "histogram" like figure on the right side uses
> "equal" size, which I think is wrong when interpret the x-axis. So, maybe
> not adding "Create New Custom" into Histogram menu?
> > <
> https://cloud.githubusercontent.com/assets/2423887/12163413/a2c410fe-b4ca-11e5-909a-789fe9572535.png
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/lixun910/geoda/issues/275#issuecomment-169564715>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/275#issuecomment-169687951>.
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
