### ISSUE TITLE
Table - read table from csv problem with large integers

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#281]
When loading a csv file with large integers (e.g., census tract code), these are converted to negative values. csv file was loaded by dropping it in the load file dialog. I believe this was an earlier ticket that was reported as fixed, but it is not working properly in 1.7.67.

**Comment by lixun910** [comment]
Yes, this has been fixed in 1.7.4x. The fix is on OGR side, so it has not been ignored to include in the later releases accidentally. This and #159 should be fixed in the next release, which also addressed another similar issue on Windows platform.

**Comment by jkoschinsky** [comment]
Great, will test again in 1.7.4.
Just confirmed same problem on another dataset with Census FIPS codes in 1.7.67.

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
