### ISSUE TITLE
Table - crash upon save after adding new variable

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#284]
When working with a single dbf table (no shape file) and adding a variable, GeoDa crashes upon invoking File > Save. After reopening the dbf file, the new variable name is added, but the values are empty (0).
The calculation is:
(1) add new variable, as integer
(2) set variable to enumerate, i.e., create an index
using 1.7.69

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
