### ISSUE TITLE
Table - add variable, no option where to position the variable

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#285]
When working with a single table (no shape file), the menu option to add a new variable does not (no longer?) provide the option as to where the variable goes, i.e., after variable x, or before variable x.
The new variable is always placed at the back. Placing it anywhere in the table, e.g., as the first variable, should be an option.

**Comment by lixun910** [comment]
This was changed (not allow user to set position of a specific column) due
to the introducing of database connections -- column position is not able
to be set in database table.

I've talked this issue with Julia, and we decide the solution to be:
auto-detect the type of the datasource, if it's file-type data, then allow
reposition; if it's database, then disable the reposition option.




Xun Li, Ph.D

Research Scientist
GeoDa Center for Geospatial Analysis and Computation
School of Geographical Sciences and Urban Planning
Arizona State University
http://www.public.asu.edu/~xunli/cv.html

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.75 (OSX El Capitan) and Win 7 Professional (64-bit).
