### ISSUE TITLE
Table - move variable position is not saved

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#286]
When manually moving the position of a variable in a single table (no shape), i.e., by dragging the column header over to a new position, the new position is not saved with File > Save. The file saves properly, but the position is unaltered. This is counterintuitive.

**Comment by lixun910** [comment]
Move variable position will be saved when connect to a file-type datasource.
Move variable position will not be allowed when connect to a database-type or read-only datasource.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.75 (OSX El Capitan) and Win 7 Professional (64-bit).
