### ISSUE TITLE
classic regular regression, spatial lag, spatial error

### ISSUE THREAD

**Issue by lixun910** [lixun910/geoda#290]
It crashed with a US. census tract polygon shapefile
![unnamed 2](https://cloud.githubusercontent.com/assets/2423887/11998478/e0cf1730-aa5d-11e5-94a8-830993d374ea.png)

**Comment by lixun910** [comment]
This can't be reproduced after several related fixes of weights. One possible reason for this crash is out-of-memory, since this dataset will take up 1.5 Gb memory.

**Comment by jkoschinsky** [comment]
GeoDa 1.7.87

Steps: 
1. Load tract shapefile (will send link in separate message, 400+MB)
in Win 7 Professional (64-bit): unhandled exception error message

In OSX Yosemite, 10.10.5
2. Add basemap --> crash
but then I tried again and it loads the basemap ok

Weights creation, histogram and connectivity map all created within seconds, which is impressive since file has over 73k records.

If you can try on your end to see if you can replicate the crash.

**Comment by lixun910** [comment]
tested on my side OSX 10.6 10.10 Windows 7 32bit. Works fine. This data loading takes 1,5 Gb memory. Can you verify again? Thanks! 
![screen shot 2016-03-04 at 1 57 52 pm](https://cloud.githubusercontent.com/assets/2423887/13540007/4ae0e046-e211-11e5-8aac-41ad2f655a85.png)

**Comment by jkoschinsky** [comment]
right - loading works fine but creation of distance matrix took over 20
 min and still spinning so I force-quit.

On 4 March 2016 at 13:59, Xun Li <notifications@github.com> wrote:

> tested on my side OSX 10.6 10.10 Windows 7 32bit. Works fine. This data
> loading takes 1,5 Gb memory. Can you verify again? Thanks!
> [image: screen shot 2016-03-04 at 1 57 52 pm]
> <https://cloud.githubusercontent.com/assets/2423887/13540007/4ae0e046-e211-11e5-8aac-41ad2f655a85.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/290#issuecomment-192465101>.
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by lixun910** [comment]
Just tested: contiguity and KNN weights can be created in seconds. Threshold weights using bydefault value hands their -- I think that's because the by default value are too large, which makes every polygon searches too many neighbors (considering 73K records). Should user takes own risk of what a reasonable threshold should be input especially for a relatively large dataset?

**Comment by jkoschinsky** [comment]
yes, that's fine. We can close this.
