### ISSUE TITLE
LOWESS regression crashed on 64-bit windows 

### ISSUE THREAD

**Issue by lixun910** [lixun910/geoda#292]
The algorithm of LOWESS regression has a bug when use std::partial_sort() function. It's definition is:

template< class RandomIt >
void partial_sort( RandomIt first, RandomIt middle, RandomIt last );

The usage in ShapeOperations\Lowess.cpp gives wrong parameters, and cause "invalid iteration" error and a crash. 

This error has been ignored on Mac OSX as well as  32-bit windows (no crash on these platforms).

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.87 ( Win 7 Professional (64-bit): No more crash.

Could you confirm that the iterations are active: Nothing changes for different iterations, even in small datasets. If it's active, you can close the ticket.

**Comment by lixun910** [comment]
Verified via debug, the iterations are active.
