### ISSUE TITLE
Shapefile load problem

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#296]
This shapefile loads ok in CartoDB but not in GeoDa 1.7.75-new (Mac OSX)
[sample data.zip](https://github.com/lixun910/geoda/files/107621/sample.data.zip)
.

**Comment by lixun910** [comment]
![screen shot 2016-01-27 at 9 19 41 pm](https://cloud.githubusercontent.com/assets/2423887/12635004/f2b06596-c53b-11e5-815a-fe1d9478d94d.png)
Just tried it on my side. It's working. What's the error message?

**Comment by jkoschinsky** [comment]
Here it is. Can show you in person at our mtg so we can look at  log files.
<img width="422" alt="screen shot 2016-01-28 at 6 47 20 am" src="https://cloud.githubusercontent.com/assets/13679743/12646054/16081fee-c58b-11e5-97f1-6c282549ee5e.png">

**Comment by jkoschinsky** [comment]
this problem ended up being due to special characters in the file path.

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
