### ISSUE TITLE
Averages tool DID output

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#297]
If you have no regime selected but right-click and run the DID test, you can do it but get nan output. Since users shouldn't do this, let's add a prompt to first make a selection before running DID - like we have for time periods when you try to run a DID on only one time period.
<img width="1248" alt="screen shot 2016-01-27 at 8 12 25 pm" src="https://cloud.githubusercontent.com/assets/13679743/12633920/9b683dda-c532-11e5-8127-c37df25c2233.png">

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Works well. Let's just update the error message from this:

<img width="420" alt="screen shot 2016-03-02 at 2 56 04 pm" src="https://cloud.githubusercontent.com/assets/13679743/13476882/0696d818-e087-11e5-94f2-c331840f4ca5.png">

to this:
Please first select observations in one of the other data or map views.

**Comment by lixun910** [comment]
Please verify in 1.7.87

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
