### ISSUE TITLE
Averages Tool time selection

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#298]
Attached is confusing: Time 1 is selected but in the table it shows up as time 2 and the warning message says Time 1 isn't selected. Looks like this is due to horizontal labels (Time 1) coinciding with default labels for radio buttons but referring to two different things. One solution would be to rename the default in either the Averages tool or the time editor, e.g. to Period instead of Time so they differ.

<img width="762" alt="screen shot 2016-01-27 at 8 17 20 pm" src="https://cloud.githubusercontent.com/assets/13679743/12634044/8795149e-c533-11e5-83c7-83ba99bf7871.png">

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
