### ISSUE TITLE
Icon selection in

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#300]
Win 7 Pro

At the default size of the main toolbar, the mouseover area of the icons is reduced to a thin rectangle that you have to click on in order to access the tool (see attached image). You have to enlarge the toolbar for this rectangle to become a square that covers the whole icon.

![icon selection](https://cloud.githubusercontent.com/assets/13679743/12649073/38ee760c-c59a-11e5-9c20-65437b253565.png)

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (Win 7 Professional (64-bit)).
