### ISSUE TITLE
Time Editor labels

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#301]
Move back and forward confusing since people might think this is about moving the variables back and forth from/to the left column.

Let's rename:
Move Back --> Move Up
Move Forward --> Move Down

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
