### ISSUE TITLE
Change order of export file options

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#302]
Let's change the order of the files listed for exporting space-time files to the most common ones and move SQLite from first to last position. 
![export space time](https://cloud.githubusercontent.com/assets/13679743/12649742/1e2728e8-c59d-11e5-9070-cb813c0322a9.png)

**Comment by jkoschinsky** [comment]
Same for Open Input File: Move SQLite to bottom from 2nd place.

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
