### ISSUE TITLE
Averages Chart: Edit time period labels - no close button

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#303]
When you click on the time labels of the x-axis of the Averages chart, the dialog opens to change the label names and changing them works great. Only problem is I don't see an option to close the dialog again :)

![time label editor](https://cloud.githubusercontent.com/assets/13679743/12650221/365797ac-c59f-11e5-8a2b-ad7043c222ca.png)

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
works great now.

Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
