### ISSUE TITLE
DID regression output

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#304]
Win 7 Pro

By default, the window of the DID regression output only shows parts of the result (see attached). We could either increase the window size or decrease the font like in the regular regression output.

Let's also rename the window:
Regression Report --> Diff-inDiff Regression Report

![did reg output](https://cloud.githubusercontent.com/assets/13679743/12650474/3c2bf8e8-c5a0-11e5-9695-52023767fc0b.png)

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
