### ISSUE TITLE
Averages Chart: Listing Variable Name in View Header

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#305]
Right now, the only place where the variable name is listed is on the y-axis. Let's also list it in the view header like we do for the other views.

![averages chart](https://cloud.githubusercontent.com/assets/13679743/12651043/43133886-c5a2-11e5-9da8-f55edc781659.png)

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
