### ISSUE TITLE
allow special characters in file path

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#307]
Shapefile won't open if special characters are in file path, e.g. as in this case:
/Users/XXX/XXX/GeoDa\ Center/Data/Zählsprengel_Graz_EPSG-4326 

We used to have code to handle such paths for prior versions of reading shapefiles.

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
