### ISSUE TITLE
File IO: add .gda to drag+drop open file

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#309]
Right now you can add data files to the "drop files here" area (see below) but you can't drop and drag .gda project files in here. Let's enable this so people can drag and drop data and .gda files.

<img width="516" alt="screen shot 2016-02-01 at 12 18 22 pm" src="https://cloud.githubusercontent.com/assets/13679743/12728204/e9d0c768-c8dd-11e5-9dd0-5b6b1a2f3774.png">

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
