### ISSUE TITLE
Automatically save a gda file once you create time groups

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#310]
Right now people get confused how to save their grouped variable settings (e.g. they think this is done if they choose "save"). Let's automatically save a g.da file once you create time groups so people don't lose their grouped variable specifications.

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Users need to click on save, then data are saved and project file is created (see other ticket, which prompts users to save data before closing GeoDa).

Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
