### ISSUE TITLE
Change order of "open input files"

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#313]
Right now, spatial files and text files are mixed together in the open input file list. Let's separate them to make this easier to navigate, e.g. with a line separating the two types:

ESRI Shapefile
GeoJSON
ESRI File Geodatabase
MapInfo
gml
kml

------------------------------------
csv
dbf
Excel
ODS
sqlite

**Comment by lanselin** [comment]
I would put dbf above csv, since that is the more common input of the two.

Luc Anselin, PhD
Regents’ Professor and Walter Isard Chair
Director, GeoDa Center for Geospatial Analysis and Computation
Arizona State University

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.81 (OSX Yosemite, 10.10.5). 
Still verifying in Win 7 Professional (64-bit).

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
