### ISSUE TITLE
Close weights creation dialog after creating weights?

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#316]
Right now, after you create a weights matrix you get a confirmation dialog that the weights were created and we are leaving the weights creation dialog open in case the user wants to create another weights file. 

In my experience, more experienced users create multiple weights files but many users, especially those who are starting, just create one.

I'm leaning towards closing the weights creation dialog after you create a weights file to avoid confusion by the less experienced users about why the weights dialog is still open (they might think they still need to do something else with the weights dialog).

What do you think.

<img width="840" alt="screen shot 2016-02-09 at 4 36 39 pm" src="https://cloud.githubusercontent.com/assets/13679743/12934398/73837d48-cf4b-11e5-8db4-7571c3a84484.png">

**Comment by lanselin** [comment]
I think we have moved towards keeping windows open rather than closing them.
Maybe we need a button that says “close”.

**Comment by jkoschinsky** [comment]
ok, let's just add a "close" button next to "create" so people don't assume they have to create another one to proceed.

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.81 (OSX Yosemite, 10.10.5). 
Still verifying in Win 7 Professional (64-bit).

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
