### ISSUE TITLE
Scatterplot matrix and time bug

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#317]
GeoDa 1.7.75 (OSX El Capitan) and Win 7 Professional (64-bit). 
Data: Nat.shp.

Steps:
1. Use nat.shp without time-grouped variables
2. Open a scatterplot matrix (e.g. 3x3, any variables)
3. Open time and click on play
4. Nothing happens because there are no time-grouped variables but the scatterplot matrix starts flickering (seems like based on the default timing of moving from time 0 to time 1 etc.) as if it's moving in place.

**Comment by jkoschinsky** [comment]
Same behavior with correlogram.

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.81 (OSX Yosemite, 10.10.5). 
Still verifying in Win 7 Professional (64-bit).

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
