### ISSUE TITLE
Differential Moran's I warning message text

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#318]
When you click on Differential Moran's I (Diff MI) without any time-grouped variables, you get the following warning:

<img width="421" alt="screen shot 2016-02-10 at 10 08 19 pm" src="https://cloud.githubusercontent.com/assets/13679743/12992577/7c51dee6-d0d2-11e5-9295-daeac92a6077.png">

Let's update this to the following text:

Differential Moran's I tests whether the change in a variable over time is spatially correlated.

Please first group the a variable by time period: Select Time --> Time Editor.

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
still the old message in GeoDa 1.7.81?

<img width="1219" alt="screen shot 2016-03-01 at 2 31 44 pm" src="https://cloud.githubusercontent.com/assets/13679743/13442618/61b5ecb6-dfba-11e5-8728-cdfd4174c6c5.png">

**Comment by jkoschinsky** [comment]
I see what happened: It was updated for Moran scatterplot but not LISA.

Sorry, also just noticed a typo in my text if you could update in both:
Please first group variables by time period: Select Time --> Time Editor.

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
Diff Moran's I:
Moran scatterplot fixed - LISA still has old message.

**Comment by lixun910** [comment]
Please verify in 1.7.87

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
