### ISSUE TITLE
map window icons - base map icon

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#319]
the base map icon is not very intuitive - it looks like a person,
does not suggest a base map. anything better?

**Comment by lanselin** [comment]
to clarify, in 1.7.77

**Comment by jkoschinsky** [comment]
Sure, will play with updating it in Photoshop.

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.81 (OSX Yosemite, 10.10.5). 
Still verifying in Win 7 Professional (64-bit).

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
