### ISSUE TITLE
table editor - edit variable properties

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#320]
there seems to be a problem with the conversion from string to numeric (integer or real) when the string field contains "," for thousands. in the data file i will send separately this is the case for several variables that are population totals, e.g., 126,677. this gives an error - see attached screen shot. any way to make the properties editor robust to this?
<img width="416" alt="screen shot 2016-02-20 at 3 41 28 pm" src="https://cloud.githubusercontent.com/assets/4008351/13199344/89b76f52-d7e8-11e5-9f2b-89d2649934ee.png">

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.87 (OSX Yosemite, 10.10.5).
