### ISSUE TITLE
basemap disappears after zooming in

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#321]
GeoDa 1.7.75

When you select a basemap and then zoom in, the basemap disappears instead of remaining.

**Comment by lixun910** [comment]
Tried on my side. I believe it’s a network problem. You can try the “refresh” button.

**Comment by jkoschinsky** [comment]
ok, confirmed -- must be the connection I'm on, it did work this time

On 26 February 2016 at 20:02, Xun Li <notifications@github.com> wrote:

> Tried on my side. I believe it’s a network problem. You can try the
> “refresh” button.
>
>
>
> > On Feb 26, 2016, at 8:00 PM, jkoschinsky <notifications@github.com>
> wrote:
> >
> > GeoDa 1.7.75
> >
> > When you select a basemap and then zoom in, the basemap disappears
> instead of remaining.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/lixun910/geoda/issues/321>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/321#issuecomment-189564359>.
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter
