### ISSUE TITLE
regression output formatting 

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#322]
When you use variables that were grouped by time period, the formatting of the results isn't quite aligned right yet like it is for the regular variables:

<img width="700" alt="screen shot 2016-02-27 at 1 13 38 am" src="https://cloud.githubusercontent.com/assets/13679743/13371753/54b66ee2-dcf3-11e5-8de6-36ce6ebafcac.png">

**Comment by lixun910** [comment]
Thanks, Julia! For a fix, do you want the "Number of Observation: xxx" on the second line when the variable name is too long "rentBurd50 (2008)"?

**Comment by jkoschinsky** [comment]
That sounds good, thx. I was looking at the coefficient etc. output - for that we can just push everything to the right so it lines up or truncate at a certain length to avoid crazy long variable names pushing the output out too far.

**Comment by lixun910** [comment]
check the fix in 1.7.81

**Comment by jkoschinsky** [comment]
Coefficients, St error, t-stats and p-values are still not right-aligned when variable name is too long (e.g. for %Unempl (2005) below):

<img width="533" alt="screen shot 2016-03-01 at 2 00 47 pm" src="https://cloud.githubusercontent.com/assets/13679743/13441775/3b886f2c-dfb6-11e5-8d8a-0f512735cdc1.png">

**Comment by lixun910** [comment]
Can you verify it again on 1.7.81? Here is what shows on my side:
-----------------------------------------------------------------------------
    Variable         Coefficient      Std.Error    t-Statistic   Probability
-----------------------------------------------------------------------------
          CONSTANT      379.9581       59.10306       6.428738     0.00000
      %KIDS (2008)    -0.5012114       1.856087     -0.2700365     0.78822
    %Unempl (2008)     -9.334531       5.443039      -1.714948     0.09243
      %hisp (2008)    -0.9320118      0.8398338      -1.109757     0.27231
——————————————————————————————————————

**Comment by jkoschinsky** [comment]
We could try these two things to fix this:

Right-align values in each column and standardize the decimal places to e.g. 5 - right now they range from 5 to 8 in the example below, which is why the numbers don't line up:

<img width="695" alt="screen shot 2016-03-01 at 2 43 58 pm" src="https://cloud.githubusercontent.com/assets/13679743/13444313/b9a7fcf4-dfc2-11e5-89a2-09e4b75cd8f1.png">

**Comment by lixun910** [comment]
Yes, this should be fixed. Even if you have a very long var name, see for example, I rename %KIDS  to $KIDSadfasgasdfa. That’s the output


-----------------------------------------------------------------------------
    Variable         Coefficient      Std.Error    t-Statistic   Probability
-----------------------------------------------------------------------------
          CONSTANT      107.5302       137.8513      0.7800448     0.43890
%KIDSad..fa (2008)     -1.843031       1.649879      -1.117071     0.26910
     %Owner (2008)       18.9156       9.828736        1.92452     0.05977
-----------------------------------------------------------------------------

REGRESSION DIAGNOSTICS

**Comment by jkoschinsky** [comment]
yes, perfect, I just converted the font to Courier New and it looks good:

<img width="578" alt="screen shot 2016-03-01 at 3 42 13 pm" src="https://cloud.githubusercontent.com/assets/13679743/13444562/4258ac64-dfc4-11e5-89dc-e3b7b56d11e7.png">

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
right-alignment looks good but decimal degrees of results still vary:

<img width="589" alt="screen shot 2016-03-02 at 2 31 14 pm" src="https://cloud.githubusercontent.com/assets/13679743/13476123/9321a816-e083-11e5-8e72-b20cd679a826.png">

**Comment by lixun910** [comment]
Consider what discussed yesterday "the decimal point/position is difficult to adjust with same length". Do we leave it as is now?

**Comment by lixun910** [comment]
wont' fix

**Comment by jkoschinsky** [comment]
ok, right-aligning works

Verified fix in GeoDa 1.7.91 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
