### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#323]
Got GeoDa 1.7.75 to crash:

1. open project with time-grouped variables (attached data)
[nyc2.zip](https://github.com/lixun910/geoda/files/149252/nyc2.zip)

2. open LISA map

Nothing happens.

Then open Getis-Ord, select cluster map - crash.
Replicable.

<img width="449" alt="screen shot 2016-02-27 at 1 47 47 am" src="https://cloud.githubusercontent.com/assets/13679743/13371793/356432f8-dcf4-11e5-99f3-8c36cab42f61.png">

**Comment by lixun910** [comment]
Hi Julia,

Did you create the project file manually? The weights file information in the project file is incorrect, and caused this crash. However, any incorrect information in project file should be detected and reported to user not a crash anyway, and I will fix this. 

For a workaround for your testing, using the following project file to replace your original one.
[nyc4.gda.zip](https://github.com/lixun910/geoda/files/149454/nyc4.gda.zip)

**Comment by jkoschinsky** [comment]
Hi Xun,

Yes, I did create it manually. I'll test this some more since I was getting
some duplicative save requests when I tested yesterday but have to
replicate.

On 27 February 2016 at 10:39, Xun Li <notifications@github.com> wrote:

> Hi Julia,
>
> Did you create the project file manually? The weights file information in
> the project file is incorrect, and caused this crash. However, any
> incorrect information in project file should be detected and reported to
> user not a crash anyway, and I will fix this.
>
> For a workaround for your testing, using the following project file to
> replace your original one.
> nyc4.gda.zip <https://github.com/lixun910/geoda/files/149454/nyc4.gda.zip>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/323#issuecomment-189687755>.
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by lixun910** [comment]
check the fix in 1.7.81

**Comment by jkoschinsky** [comment]
Hi Xun, 
Luc just ran into the same issue:

i saw a thread yesterday about issues with a project file.
i tried the nyc4.gda project file you shipped with the new nyc
data and ran into some issues.
not sure if this is something that needs to be fixed or is something
else:
- the name of the weights file in the gda file is misspelled, i corrected
- the gda file points to the dbf file in the subdirectory nyc_sampledata,
  but the weights are not recognized; somehow it does not keep the
  path information for the weights
so, after i edited the weights file name and moved the weights to
the same directory as the gda file, it worked.
i would think that it should use the same path for the data and for the
weights. is this something that was fixed, or did the path somehow
get changed during various operations?

**Comment by lixun910** [comment]
HI Julia,

Did you get my email for 1.7.81 build?  I’ve added checking code if the weights file path is invalid. 

The path could be relative path or positive path, for manual editing the project file, you have to make sure it’s correct, unless you can save it from GeoDa.

Xun

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
