### ISSUE TITLE
Add option to start displaying Y-axis values at 0 for averages chart

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#324]
Currently small differences between values of different time periods are exaggerated because we're not displaying values on the Y-axis starting from zero, e.g.: 

![image](https://cloud.githubusercontent.com/assets/13679743/13413908/5d97abd8-df0b-11e5-98e5-3cf55fc1570d.png)

Let's add the option to start displaying values from zero to avoid this exaggeration of differences (on the other hand, starting from zero might compress differences too much but with an option users can try both).

Doesn't have to be added in 1.8, especially if this takes longer to do.

**Comment by lixun910** [comment]
We can't just simply use "zero" as an "adjustment" point for any yValues. For example, if the y value ranges from -100 ~ 100, then "zero" will not work; or if use "population" as y value, "zero" also won't work. Maybe let the user input the value of start point on Y-Axis or the range of Y-Axis (like python users often do in matplotlib)? 

The exaggeration of differences are only visual impression. Users can always resize the window to change the visual impression and check the stats.

**Comment by jkoschinsky** [comment]
sure, user input for starting point as option would work

On 1 March 2016 at 13:21, Xun Li <notifications@github.com> wrote:

> We can't just simply use "zero" as an "adjustment" point for any yValues.
> For example, if the y value ranges from -100 ~ 100, then "zero" will not
> work; or if use "population" as y value, "zero" also won't work. Maybe let
> the user input the value of start point on Y-Axis or the range of Y-Axis
> (like python users often do in matplotlib)?
>
> The exaggeration of differences are only visual impression. Users can
> always resize the window to change the visual impression and check the
> stats.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/324#issuecomment-190860750>.
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by lixun910** [comment]
Proposed fix.
![screen shot 2016-03-01 at 3 53 31 pm](https://cloud.githubusercontent.com/assets/2423887/13444848/0125da08-dfc6-11e5-96c1-0b8c6dc344d7.png)

**Comment by jkoschinsky** [comment]
Looks great. I'll test it with next release.

On 1 March 2016 at 15:55, Xun Li <notifications@github.com> wrote:

> Proposed fix.
> [image: screen shot 2016-03-01 at 3 53 31 pm]
> <https://cloud.githubusercontent.com/assets/2423887/13444848/0125da08-dfc6-11e5-96c1-0b8c6dc344d7.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/324#issuecomment-190948433>.
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
You can do some funky things by specifying a value range that does not match that of the variable, e.g. in this case the specified range is too narrow:

<img width="803" alt="screen shot 2016-03-01 at 10 39 22 pm" src="https://cloud.githubusercontent.com/assets/13679743/13451692/9ada5984-dffe-11e5-80b4-3913af760e3d.png">

or you can specify min-max values totally outside of the variable's range in which case you see nothing :)
If it's easy to restrict the specified min and max to the variable range, this would solve the problem.

**Comment by lixun910** [comment]
Please verify in 1.7.89

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.89.
