### ISSUE TITLE
invert selection map icon

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#325]
Luc: invert selection icon is confusing. Can we go back to old one with new color scheme?

<img width="40" alt="screen shot 2016-02-29 at 5 42 12 pm" src="https://cloud.githubusercontent.com/assets/13679743/13413966/e5b4d702-df0b-11e5-830f-b783658eb11c.png">

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
still the same?

<img width="663" alt="screen shot 2016-03-01 at 9 44 13 pm" src="https://cloud.githubusercontent.com/assets/13679743/13450841/c8d72bda-dff6-11e5-9072-40d04df05dc0.png">

**Comment by jkoschinsky** [comment]
sorry, wrong version!

**Comment by lanselin** [comment]
fixed in 83

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
