### ISSUE TITLE
save image as creates strange files

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#326]
invoking save image as for a box plot creates the following file with a png.svg file extension.
two questions:
- why double file extension ("SVG Picture created as Nepal_District2BoxPlotFrame.png.svg")
- why is the image information lost
see attached screen shots
using 1.7.81
<img width="349" alt="screen shot 2016-02-29 at 6 56 06 pm" src="https://cloud.githubusercontent.com/assets/4008351/13414227/8dbc9b7e-df16-11e5-9ec6-c0199c01a311.png">
<img width="443" alt="screen shot 2016-02-29 at 6 55 52 pm" src="https://cloud.githubusercontent.com/assets/4008351/13414232/95baa776-df16-11e5-8843-9f2b952fbba3.png">

**Comment by lanselin** [comment]
problem seems to be with svg only; png and bmp work fine.
however, svg is the default, which is a problem.

**Comment by lanselin** [comment]
and file extensions need to be fixed, they are all double, e.g., png.bmp

**Comment by lixun910** [comment]
Just verified on my side. I think it's a problem of wxwidgets svg (wxSVGFileDC). But, we can't control how wx converts the drawing to a svg file. We could test if the latest wxwidgets fix this issue. 

How about changing the default save option from svg to png?

**Comment by jkoschinsky** [comment]
I think we have a ticket on this or very similar issue

**Comment by lanselin** [comment]
if it doesn't work, we should remove the svg option (for now); also need to fix the file extension

**Comment by lixun910** [comment]
Got it. This will be verified and fixed.

Xun

**Comment by jkoschinsky** [comment]
see also https://github.com/lixun910/geoda/issues/214

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
png and bmp only options.
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
