### ISSUE TITLE
histogram interval choice requires click

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#327]
the selection of intervals in the histogram requires an explicit click on OK.
pressing the return key does not work. this is not consistent with other dialogs,
where pressing the return key and clicking on OK are equivalent.

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
