### ISSUE TITLE
histogram custom classification - problems with category editor

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#328]
when selecting create new custom classification in a histogram, the next interface is a dialog for 
New Custom Categories Title;
when clicking OK, this applies a default classification, but does not close, instead additional names
are generated.
this seems counterintuitive: clicking OK should bring up the Category Editor interface, now one
needs to click cancel to get there (but that doesn't alway work, one has to click cancel several
times).
i don't think that dialog should be there, since one can create a new name using the New button
in the interface. also, when the category editor is invoked separately, there is no such dialog.

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
Create New Custom opens Category Editor directly now.
