### ISSUE TITLE
project file error msg text

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#329]
Update this error message:

<img width="1026" alt="screen shot 2016-02-29 at 7 59 03 pm" src="https://cloud.githubusercontent.com/assets/13679743/13416391/64e22724-df1f-11e5-84b5-bd5fac11411a.png">

to this:

This project file cannot find one or more associated weights file(s). Please make sure the weights file(s) are in the same directory as your spatial file.

Advanced tip: You can open the .gda project file in a text editor to find the name(s) of the weights file(s) (.gwt or .gal extension) associated with your project.

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
Current:

<img width="425" alt="screen shot 2016-03-01 at 10 18 46 pm" src="https://cloud.githubusercontent.com/assets/13679743/13451371/adde6bf4-dffb-11e5-814c-0174d1aea752.png">

Updated:

The GeoDa project file cannot find one or more associated data sources.

Details: File GeoDa is looking for: XXX

Tip: Move the project file in the same directory as the spatial files. You can also edit the project file (.gda) in a text editor to modify the path of the associated data source.

**Comment by lixun910** [comment]
Please verify in 1.7.87

**Comment by jkoschinsky** [comment]
Two minor changes:

Details:
Datasource not exists: --> File GeoDa is looking for: 

Tip:
datasource --> data source.

**Comment by jkoschinsky** [comment]
still the same message when you drag a gda file into "drop files here":

<img width="417" alt="screen shot 2016-03-05 at 12 48 45 am" src="https://cloud.githubusercontent.com/assets/13679743/13546464/19f268b4-e26c-11e5-87b4-656117529b3c.png">

**Comment by lixun910** [comment]
<img width="421" alt="screen shot 2016-03-05 at 2 48 20 pm" src="https://cloud.githubusercontent.com/assets/2423887/13550727/5f7c66ee-e2e1-11e5-9c95-9aad6055170e.png">

**Comment by lixun910** [comment]
please verify in 1.7.91

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.91 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
