### ISSUE TITLE
Text for 3rd ? in Time Editor

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#330]
Update this error message:

<img width="422" alt="screen shot 2016-02-29 at 8 20 17 pm" src="https://cloud.githubusercontent.com/assets/13679743/13416748/2ed227e4-df22-11e5-84ad-df52b93e10b5.png">

to this:

This is the list of existing grouped variables. As new groups are created, they will appear on this list. You can open an existing .gda file and edit it here.

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
