### ISSUE TITLE
Text for 1st ? in time editor

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#331]
Update this text:

<img width="420" alt="screen shot 2016-02-29 at 8 25 34 pm" src="https://cloud.githubusercontent.com/assets/13679743/13416818/b0cc5f58-df22-11e5-843f-ba958117298e.png">

to this:

List of existing ungrouped variables. To group variables by time, move them to the list on the right. 
For example, to group Pop80 and Pop90, select them on the left and move them to the right.

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
