### ISSUE TITLE
Text for 2nd ? in Time Editor

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#332]
Replace this text:

<img width="418" alt="screen shot 2016-02-29 at 10 40 44 pm" src="https://cloud.githubusercontent.com/assets/13679743/13418758/8ce42a0e-df35-11e5-806f-c64fc1e2e576.png">

with this one:

Add a name for your group of variables. 
You can edit the time period labels for easier interpretation of results.

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
