### ISSUE TITLE
boxplot right-click: Point color not working

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#333]
GeoDa 1.7.81

<img width="547" alt="screen shot 2016-02-29 at 11 19 53 pm" src="https://cloud.githubusercontent.com/assets/13679743/13420016/df6f3db8-df3f-11e5-9419-3975700cb9b4.png">

Boxplot: right-click --> Color --> Point color 
does not seem to be working (other color options are fine)

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
