### ISSUE TITLE
Update error messages 

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#334]
Current:
error_message << "Current data source format " << format << " is not supprted by GeoDa.\n" <<

Update:
error_message << "This data source format " << format << " is not supported by GeoDa.\n" <<

------------------------------------------------------------------------------------------------------------------------------------

Current:
wxMessageBox("Wrong format!");

Update:
wxMessageBox("This format is not supported.");

------------------------------------------------------------------------------------------------------------------------------------
Current:
wxLogMessage("Error: could not read " + input_dbf);

Update:
wxLogMessage("Error: GeoDa could not read " + input_dbf);

------------------------------------------------------------------------------------------------------------------------------------
Current:
wxMessageBox("the file is Unsupported type!");

Update:
wxMessageBox("This file type is not supported.");

------------------------------------------------------------------------------------------------------------------------------------
Current:
wxMessageBox("Select options!");

Update:
wxMessageBox("Please select an option.");

------------------------------------------------------------------------------------------------------------------------------------
Current:
wxString msg("Please select a Result field.");

Update:
wxString msg("Please select a results field.");
------------------------------------------------------------------------------------------------------------------------------------
Current:
wxMessageBox("Can't Save file");

Update:
wxMessageBox("GeoDa was unable to save the file");
------------------------------------------------------------------------------------------------------------------------------------

Current:
error_message << "GeoDa does not support creating data source "
463				<< "of " << ds_format << ". Please try to 'Export' to other "

Update:
error_message << "GeoDa does not support creating data "
463				<< "of " << ds_format << ". Please try to 'export' to other "
------------------------------------------------------------------------------------------------------------------------------------

Current:
wxString msg("Error: Table variable name empty.");

Update:
wxString msg("Error: The table variable name is empty.");
------------------------------------------------------------------------------------------------------------------------------------
Current:
wxMessageBox("Fatal Excption.  Program will likely close now.");

Update:
wxMessageBox("GeoDa has run into a problem and will close.");

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
I accessed the error messages through the GitHub code instead of through the GUI, so I'll close this ticket since you updated the code.
