### ISSUE TITLE
Updated error messages 2

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#335]
Current message:
wxMessageDialog dlg(NULL, "There is no layer found in selected datasource.", "Info", wxOK | wxICON_INFORMATION);

Updated message:
wxMessageDialog dlg(NULL, "No layer was found in the selected data source.", "Info", wxOK | wxICON_INFORMATION);
----------------------------------------------------------------------------------------------------------------------------------
Current message:
 msg << "Failed to open data source. Please check if the data is valid and its data type/format is supported by GeoDa.\n\nTip: you can setup necessary GeoDa driver by following the instructions at:\n https://geodacenter.asu.edu/geoda/formats";

Updated message:
 msg << "Failed to open data source. Please check the data and check if the data type/format is supported by GeoDa.\n\nTip: you can set up the necessary GeoDa driver by following the instructions at:\n https://geodacenter.asu.edu/geoda/formats";
----------------------------------------------------------------------------------------------------------------------------------
Current message:
wxString DUP_WARN = "Duplicated field name.";

Updated message:
wxString DUP_WARN = "Duplicate field name.";
----------------------------------------------------------------------------------------------------------------------------------

Current message:
		wxString msg("Selected field is not a numeric type.  Please report "

Updated message (please check that this is correct):
		wxString msg("Selected field should be numeric."

----------------------------------------------------------------------------------------------------------------------------------

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
I accessed the error messages through the GitHub code instead of through the GUI, so I'll close this ticket since you updated the code.
