### ISSUE TITLE
Time editor: Open gda file option

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#336]
Is the "open gda file" option no longer in the time editor of GeoDa 1.7.81 next to grouped variables? 
I was just using it in the previous version and it worked great/was really useful.

<img width="669" alt="screen shot 2016-03-01 at 1 40 03 pm" src="https://cloud.githubusercontent.com/assets/13679743/13441205/52006654-dfb3-11e5-8ed3-1acc9cc1129b.png">

**Comment by lixun910** [comment]
Hi Julia,

Can you verify this issue again with the latest build 1.7.81? Mine works
fine. Thanks!

Xun

**Comment by jkoschinsky** [comment]
Yes, my mistake, I had two versions of GeoDa open and used the previous one, which is why I closed the ticket again, so this one is done, thx.
