### ISSUE TITLE
Connect to Data Source: Loading .gda project file

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#337]
When I load nyc4a.gda below, I get the enclosed error message. When I load nyc4.gda, it opens fine. So it looks like the error is related to a path problem but the error message suggests it's a file type problem. For this case, let's instead use the other error message we had that suggested people put the .gda file in the same directory as their spatial file.

<img width="1046" alt="screen shot 2016-03-01 at 1 44 20 pm" src="https://cloud.githubusercontent.com/assets/13679743/13441361/e198c194-dfb3-11e5-8645-12fb8153aa93.png">

**Comment by lixun910** [comment]
please verify in 1.7.91

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.91.
