### ISSUE TITLE
Replicable crash: Time Editor and loading .gda file

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#338]
GeoDa 1.7.81

Found a replicable crash (used NYC shapefile and .gda file):

1. Open a shapefile
2. Then open time editor
3. Load a .gda file from a different directory (or one that doesn't match the shapefile's dbf)
4. GeoDa crashes

For this case, let's use same error message as for File IO re. putting the gda in the same directory and checking the gda file in text editor for weights etc. file names.

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
