### ISSUE TITLE
Update Diff Moran's I weights warning

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#339]
Current:

<img width="415" alt="screen shot 2016-03-01 at 2 20 14 pm" src="https://cloud.githubusercontent.com/assets/13679743/13442299/bd772602-dfb8-11e5-998c-b41f24061708.png">

Updated:

GeoDa could not find the required weights file.
Please specify weights in Tools > Weights Manager.

**Comment by lixun910** [comment]
please verify in 1.7.83

**Comment by jkoschinsky** [comment]
GeoDa 1.7.85
The error messages for Diff Moran global and LISA aren't synched:

e.g. for nat.shp without weights loaded:
1. open Diff Moran's I for LISA: You get the weights error (with message not updated yet, see other ticket)
2. open Diff Moran's I for Moran scatterplot: you get time editor error

Let's synch this so that for both global and local we first ask users to specify weights and then time (or vice versa, doesn't matter).

**Comment by lixun910** [comment]
Please verify in 1.7.87

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
