### ISSUE TITLE
Export dbf to csv fails

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#340]
I loaded a dbf file (it's non-public data, will email) and then tried to export it as a csv and got the following error message:
 
<img width="1170" alt="screen shot 2016-03-01 at 4 06 05 pm" src="https://cloud.githubusercontent.com/assets/13679743/13445125/b27e1f9e-dfc7-11e5-99c9-ebe91761d706.png">

**Comment by lixun910** [comment]
I should not call this a "rare" case since it's common to have empty string in a string column. Will try to look more in OGR side to make sure it's fixed.

**Comment by lixun910** [comment]
please verify in 1.7.85

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)) using other dbf from Meagan with missing string fields.
