### ISSUE TITLE
Prompt user to save data before exiting GeoDa

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#341]
Right now users aren't prompted to save their data: If they exit without it, they will lose changes made to the dbf and gda file (or won't have created a gda file).

To prevent this, prompt users to save their data when they select close.

Message:
Do you want to save your changes? 

This will also automatically create a project file, which saves your time grouped variables and weights specifications.

**Comment by lixun910** [comment]
please verify in 1.7.85

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
