### ISSUE TITLE
Moran Scatterplot Permutations: Run button disappeared

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#342]
GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).

For Moran Scatterplot - Permutations: Somehow the run button disappeared! You can access it via right-click but there's no longer a button (both Mac and Win):

<img width="549" alt="screen shot 2016-03-02 at 12 36 12 pm" src="https://cloud.githubusercontent.com/assets/13679743/13472827/c391f6e6-e073-11e5-9da1-a3e22cea3093.png">

**Comment by lixun910** [comment]
Yes, that’s what I want it to be because the button on the graph looks bad to me. Let me know if you want the button back. 

You are get used to see the button there:)

**Comment by lixun910** [comment]
please verify in 1.7.85

**Comment by jkoschinsky** [comment]
it's back ;)

Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
