### ISSUE TITLE
Averages Chart: Bottom of X-axis labels truncated a bit in Windows

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#343]
GeoDa 1.7.83 (Win Pro 64-bit).
Averages Chart: The bottom of the X-axis labels gets truncated a bit in Windows, even after resizing the window:

![avgchart2](https://cloud.githubusercontent.com/assets/13679743/13474780/c5312b12-e07c-11e5-8b3d-0563cae21efd.png)

**Comment by lixun910** [comment]
Please verify in 1.7.87

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.87 (Win 7 Professional (64-bit)).
