### ISSUE TITLE
Time Editor: Error when trying to remove time periods

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#345]
GeoDa 1.7.85, NYC data

1. Open Time Editor
2. Pull over 6 variables from ungrouped to new group
3. then try to remove three of them (right-click: remove)
4. then you get this:

<img width="855" alt="screen shot 2016-03-02 at 2 47 33 pm" src="https://cloud.githubusercontent.com/assets/13679743/13476620/ed135d22-e085-11e5-9597-46c2caf1caa6.png">

**Comment by lixun910** [comment]
Please verify in 1.7.87

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
