### ISSUE TITLE
Save selection

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#347]
Steps:

1. Select area in map
2. right-click on map: Save selection
3. Add new variable (in example below: SELECT and SELECT2)

Problem: Neither SELECT and SELECT2 show up as choice in the save selection variable choice dropdown (starts with (bor_sub and they're not otherwise on the list) 

<img width="756" alt="screen shot 2016-03-02 at 9 34 31 pm" src="https://cloud.githubusercontent.com/assets/13679743/13484899/416fecd0-e0bf-11e5-8640-0e11f400f780.png">

If you select an existing variable (like bor_sub), then you get this error message, which is confusing since you're saving a selection as 0-1 integers, so the numeric type message doesn't make sense (unless the point is that a field formatted as string can't be used to save integers to. 

<img width="620" alt="screen shot 2016-03-02 at 9 33 03 pm" src="https://cloud.githubusercontent.com/assets/13679743/13484952/efed26ba-e0bf-11e5-9cb1-9822a331ad9f.png">

I would simplify the whole thing and skip "add variable/target variable/ time" and just have selected/unselected (with edit option 0-1) and Apply. Once you hit apply a new variable is added to the table with 1 for selected, 0 otherwise (or whatever other value you specify).

**Comment by jkoschinsky** [comment]
we should also make this consistent with the selection tool.

**Comment by lixun910** [comment]
![screen shot 2016-03-03 at 12 00 20 pm](https://cloud.githubusercontent.com/assets/2423887/13505705/8e5d9dda-e137-11e5-8067-0f6acdb00d7b.png)

A simple dialog has been proposed. User just need to click "Apply" button, if they agree with the by default setting: a integer variable name "SELECTED", and 1/0 for "select/unselect". Or they can specify the variable name and the values for "select/unselect".

**Comment by jkoschinsky** [comment]
this looks good - checked it in .87 but doesn't look like it's in this version yet

**Comment by lixun910** [comment]
Please verify in 1.7.89

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.89 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
