### ISSUE TITLE
Text for "Save themeless categories"

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#348]
The last characters of "categories" get truncated  by default (can't be fixed by resizing window): "s" missing in OSX and "es" missing in Windows:

<img width="366" alt="screen shot 2016-03-02 at 9 31 55 pm" src="https://cloud.githubusercontent.com/assets/13679743/13485150/ee785776-e0c1-11e5-880c-4f87caefacb9.png">

**Comment by lixun910** [comment]
Please verify in 1.7.87

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).

**Comment by jkoschinsky** [comment]
problem still persists in Windows (1.7.87):
![save cats](https://cloud.githubusercontent.com/assets/13679743/13508984/90611f8a-e146-11e5-8839-a79890da845f.png)

**Comment by lixun910** [comment]
Please verify in 1.7.89

**Comment by jkoschinsky** [comment]
GeoDa 1.7.89
Problem fixed in OSX Yosemite, 10.10.5.
But problem persists in Win 7 Professional (64-bit): Still looks the same as in 2nd screenshot above.

**Comment by lixun910** [comment]
<img width="383" alt="screen shot 2016-03-05 at 3 43 56 pm" src="https://cloud.githubusercontent.com/assets/2423887/13551038/197d0b96-e2e9-11e5-9a9b-6cd89f76a5c1.png">
1.7.83 windows

**Comment by lixun910** [comment]
please verify in 1.7.91

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.91 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
