### ISSUE TITLE
Replicable correlogram crash

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#350]
Replicable crash:

1. Open data I'll email since it's not public
2. Open correlogram with this specification
3. click apply --> crash

<img width="861" alt="screen shot 2016-03-03 at 6 35 05 pm" src="https://cloud.githubusercontent.com/assets/13679743/13515483/de413a5a-e16e-11e5-86fd-316c7b3a2dd3.png">

<img width="449" alt="screen shot 2016-03-03 at 6 34 41 pm" src="https://cloud.githubusercontent.com/assets/13679743/13515480/d572e810-e16e-11e5-867d-5b6e3af10ae8.png">

**Comment by lixun910** [comment]
This is caused by a all zero column "LISA_P". However, GeoDa should raises a warning box not a crash. Will fix this.

**Comment by lixun910** [comment]
Please verify in 1.7.89

**Comment by jkoschinsky** [comment]
Update text from:

<img width="419" alt="screen shot 2016-03-05 at 12 36 09 am" src="https://cloud.githubusercontent.com/assets/13679743/13546406/78ffad00-e26a-11e5-8698-ae481401d042.png">

to this:
Please check your variable, e.g. make sure it is not a constant.

**Comment by lixun910** [comment]
please verify in 1.7.91

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.91 (OSX Yosemite, 10.10.5).
