### ISSUE TITLE
Location where weights are saved: update to new folder

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#354]
from Luc:
When one switches directories, the weights manager does not keep track of the new directory. For example, I used nepal to create a weights file, then i closed that and loaded nyc to create a weights file and that is saved in the nepal folder.

**Comment by lixun910** [comment]
please verify in 1.7.91

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.91 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
