### ISSUE TITLE
DF values in the Averages Chart

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#355]
something is wrong with the DF values in the Averages Chart?

from Luc:
what does D.F. stand for in the averages chart?
for example, in Nepal i selected 36 zone and
D.F. is 65.63. not sure what this is.

**Comment by lixun910** [comment]
From the code: D.F. degree of freedom:
// Estimating the combined degrees of freedom we using the
// Welch-Satterthwaite approximation:

**Comment by lixun910** [comment]
Here is the math:
s0 the first variable, s1 the second variable.

deg_free = pow(s0.var/s0.sz_d + s1.var/s1.sz_d, 2) / 
		(pow(s0.var/s0.sz_d,2)/(s0.sz_d-1) +  pow(s1.var/s1.sz_d,2)/(s1.sz_d-1) );

**Comment by jkoschinsky** [comment]
This should be based on N, not N*t

**Comment by lixun910** [comment]
Got it. Will fix.

**Comment by lixun910** [comment]
please verify in 1.7.91

**Comment by jkoschinsky** [comment]
Something still isn't right with N - it looks like we're still using N*t:

E.g. in the example below, the NYC map and table show that N = 55. 
But the obs count for selected/unselected is 24 + 141 = 165 (= 3*55) instead of 55, which it should be. The DF is 164 instead of 54. 

<img width="1439" alt="screen shot 2016-03-06 at 2 03 32 pm" src="https://cloud.githubusercontent.com/assets/13679743/13557000/54cb4daa-e3a4-11e5-80b0-3778eac6e4d6.png">

**Comment by jkoschinsky** [comment]
could you also adjust the obs count to be N?
currently still N*t

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.95.
