### ISSUE TITLE
Bubble chart text cut off

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#356]
text cut off:
<img width="367" alt="screen shot 2016-03-05 at 4 41 54 pm" src="https://cloud.githubusercontent.com/assets/13679743/13551285/681d37a0-e2f1-11e5-9059-c7342eda35ca.png">

**Comment by lixun910** [comment]
please verify in 1.7.91

**Comment by jkoschinsky** [comment]
GeoDa 1.7.91 (OSX Yosemite, 10.10.5), Nepal data

Problem persists -- use two lines instead?
<img width="401" alt="screen shot 2016-03-06 at 12 15 40 pm" src="https://cloud.githubusercontent.com/assets/13679743/13556376/682ddd40-e395-11e5-82a8-03c6a01b1391.png">

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.95 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
