### ISSUE TITLE
Replicable crash

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#357]
GeoDa 1.7.89, Nepal data

This is a specification that doesn't make sense but we should block it since it currently crashes:

1. specify three string variables in the Time Editor as one group
2. use this group in Differential Moran's I

crash

**Comment by lixun910** [comment]
please verify in 1.7.91

**Comment by jkoschinsky** [comment]
GeoDa 1.7.91 (OSX Yosemite, 10.10.5), Nepal data.

Crash persists with grouped string variables - now I get to the cluster/significance map/Moran's I dialogue and then it crashes.

Steps:
1. Group three string variables
2. specify this group in differential Moran's I (LISAs)

crash

**Comment by jkoschinsky** [comment]
Bug fixed.

Update text from:
<img width="419" alt="screen shot 2016-03-06 at 10 06 24 pm" src="https://cloud.githubusercontent.com/assets/13679743/13561226/b85728ce-e3e7-11e5-83df-37239ee0dbd6.png">

to:
The selected variable is not numeric. Please select another variable.

(add period at end)

**Comment by lixun910** [comment]
<img width="425" alt="screen shot 2016-03-06 at 10 38 11 pm" src="https://cloud.githubusercontent.com/assets/2423887/13561589/2e58e856-e3ec-11e5-8600-7935c25a1deb.png">

fix in 1.8.1

**Comment by jkoschinsky** [comment]
also good to go

On 6 March 2016 at 22:38, Xun Li <notifications@github.com> wrote:

> [image: screen shot 2016-03-06 at 10 38 11 pm]
> <https://cloud.githubusercontent.com/assets/2423887/13561589/2e58e856-e3ec-11e5-8600-7935c25a1deb.png>
>
> fix in 1.8.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/357#issuecomment-193113210>.
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.8.3.
