### ISSUE TITLE
Text for Number Separators

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#361]
Current:
Table -- Setup Number Separators
 
Update to:
Table -- Set Number Separators
-------------------------------------------------------------------------------------------------------------------------------------------
Current:
Setup Locale for GeoDa Table
 
Update to:
Set Number Separators in Table
-------------------------------------------------------------------------------------------------------------------------------------------

Current:
<img width="421" alt="screen shot 2016-03-06 at 5 36 28 pm" src="https://cloud.githubusercontent.com/assets/13679743/13558437/0072159a-e3c2-11e5-8672-35f089b2e613.png">

Update to:
Select whether to use periods or commas as separators in numeric fields. E.g., by default, GeoDa uses commas to separate thousands and periods for decimals (1,000.00).

Reset locale to system default --> Reset to default

**Comment by jkoschinsky** [comment]
can you put the 2nd sentence (e.g., ...) on a 2nd line so the box isn't that long?

**Comment by lixun910** [comment]
<img width="332" alt="screen shot 2016-03-06 at 10 36 45 pm" src="https://cloud.githubusercontent.com/assets/2423887/13561573/f7ac78c2-e3eb-11e5-9e5c-00cd0e80ce4f.png">

fix in 1.8.1

**Comment by jkoschinsky** [comment]
good to go

On 6 March 2016 at 22:37, Xun Li <notifications@github.com> wrote:

> [image: screen shot 2016-03-06 at 10 36 45 pm]
> <https://cloud.githubusercontent.com/assets/2423887/13561573/f7ac78c2-e3eb-11e5-9e5c-00cd0e80ce4f.png>
>
> fix in 1.8.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/361#issuecomment-193113010>.
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.8.3.
