### ISSUE TITLE
Category editor

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#363]
GeoDa 1.7.93, Win 7 Pro, 64-bit
nat.shp

Here's another really obscure bug involving the category editor. I was able to replicate it several times and then no longer :(

1. open nat.shp
2. click on time editor
3. open category editor and create new custom breaks (my cats)
4. edit title of new custom breaks
5. close time player and editor
6. select time again and only the time player will open, not the time editor

had to close project and open it again before clicking on time would open both player and editor.

Leaving it as FYI without milestone until I can replicate.

**Comment by lixun910** [comment]
Please verify in 1.8.3

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.8.3 (OSX Yosemite, 10.10.5).
