### ISSUE TITLE
Time Editor: 

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#364]
GeoDa 1.8.1
Atlanta.shp (has a lot of variables)

1. open time editor
2. scroll down to any variable in bottom and move it to the center panel
3. GeoDa then jumps back to the top of the left panel, so you have to scroll back down

Is there an easy way to not jump up and stay where user originally scrolled to?

**Comment by lixun910** [comment]
The current solution seems not easy to remember the last position in the left list box. But there is an easy way to navigate in the list box:  you just type on your keyboard the variable you are looking for, and the list will navigate for you. For example: 

list box:
-hello
-world
-there
-are
-my
-word

When you focus on the list box, just type on keyboard “m” and “y”, the list box will automatically nav to the item “-my”.

**Comment by lixun910** [comment]
Please verify in 1.8.3

**Comment by jkoschinsky** [comment]
works well

Verified fix in GeoDa 1.8.3 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
