### ISSUE TITLE
Time Editor bug

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#365]
GeoDa 1.8.1
Atlanta dataset

This is a really obscure time editor bug we ran into today:

1. group any two variables (move from left pane to middle and right)
2. then move the group back from the right to the left pane
3. remove the time periods
4. then specify two new variables and move them from the left to the middle
5. The previous group name remains (in this case POPT) and the arrows are greyed out so you're stuck

<img width="765" alt="screen shot 2016-03-07 at 9 50 16 pm" src="https://cloud.githubusercontent.com/assets/13679743/13592412/043da4da-e4af-11e5-9d38-d9cae1cef493.png">

**Comment by lixun910** [comment]
please verify in 1.8.3

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.8.3 (OSX Yosemite, 10.10.5).

Group name still remains from previous group but that's editable.
