### ISSUE TITLE
Regression line color in scatter plot can't be changed

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#366]
GeoDa 1.8.3 Mac and Win
nat.shp

Regression line color in scatter plot set equal to point color and can't be changed e.g. in this example where it would be useful to distinguish the line color from point color:

![reg line color](https://cloud.githubusercontent.com/assets/13679743/13617394/cb6863f6-e53b-11e5-8d46-27c03cc33766.png)

**Comment by lixun910** [comment]
1.8.5 verify

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.8.3 (OSX Yosemite, 10.10.5).
