### ISSUE TITLE
Averages chart Y-axis

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#367]
This is a small issue that came up that's not crucial to fix for 1.8.3 if it takes time:

1. (which should be easy) is to set the Y-axis legend values to 2 decimals from currently 1 since I've seen a number of test cases in the last days (e.g. for indices) where the range is e.g. 0.02-0.05 and the legend will only display 0.0 across the Y-axis scale

2. my colleague is comparing averages chart results across cities and wants to use the same scale across cities. For this case, our restriction of the Y-axis scale to the min-max values of the displayed variable makes sense in most cases but is restricting in some cases. Is it possible to add the option to override this restriction, e.g. through a checkbox option in the "Adjust Value Range of Y Axis" dialogue for something like "Use unrestricted min/max values"?

**Comment by lixun910** [comment]
1.8.5 verify

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.8.3 (OSX Yosemite, 10.10.5).
