### ISSUE TITLE
save centroids inconsistencies

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#368]
when saving the centroids, there are some inconsistent error messages and saving behavior. interestingly, the error message differs between a case where a polygon shape file is "dropped" in the file open box vs when the dbf file is dropped in it.
here are the steps:
- load nepal as a shape file (drop the shp file name in the box)
- right click on the map and select save centroids
- specify a dbf file as the output
- when selecting export, an error message warns for the loss of the geometries (see attached)
- when proceeding, the file is saved as a point shape file, not just a dbf file
- in addition, the table for the point shape file does NOT contain the centroid coordinates
alternative:
- when dropping the dbf file (associated with nepal.shp) same sequence, except
  that no error message is generated (even though the full geometry is used to create the map)
fix needed:
- when specifying dbf from the file list, only the dbf file should be saved
- the dbf file should contain the centroid coordinates in the table
(need to check if same problem exists for mean center points)
<img width="420" alt="screen shot 2016-03-10 at 9 46 03 am" src="https://cloud.githubusercontent.com/assets/4008351/13673129/b22f413c-e6a5-11e5-9554-9aeb3aa5d6ff.png">

**Comment by lixun910** [comment]
Please verify in 1.8.7
