### ISSUE TITLE
save inconsistency

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#369]
when clicking on the save icon or selecting File > Save, the Export file dialog appears, which requires the file name to be specified
this is the same as selecting export, but export is really Save As, whereas Save should pertain to the same data set.
when one tries to close a data set with changes, one is prompted to save, but no export dialog appears then. so the only way to just "save" is to try to close the project.
the inconsistencies between Save, Save As and Export need to be fixed

**Comment by lixun910** [comment]
Yes, there is one case "File->Save" will prompts Export dialog:  if you add geometries (e.g. centroids) to existing Table-only datasource (e.g. csv), then click "File-Save".

Here are the proposed fixes:
1. File->Save won't prompt any dialogs anymore. It will always save changes to opened datasource.
2. Keep "File->Export" design, which acts as "Save As". (Let me know if you want rename if to "Save As")
3. When click "Close" button with changes, one is prompted to save. This "save" will be the same as (1). However, if there are newly created geometries for a Table-only datasource, a dialog will prompts to ask user if want to "Export" to a new data source which supports Table+Geometries.

**Comment by lanselin** [comment]
suggestion sounds good. I would go with Save As rather than Export, seems more intuitive.

**Comment by lixun910** [comment]
Please verify in 1.8.7

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.99 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
