### ISSUE TITLE
horizontal axis labels in histogram with custom categories

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#370]
after implementing a custom category with the category editor and applying it to a histogram, the tick marks on the horizontal axis do not seem to correspond to anything, definitely not to the cut-off values chosen in the custom category, see attached (proper cut off should have been 4, 8, 12).
<img width="558" alt="screen shot 2016-03-12 at 4 02 43 pm" src="https://cloud.githubusercontent.com/assets/4008351/13725331/4cc5a516-e86c-11e5-8e88-7b753a1c5db6.png">
<img width="719" alt="screen shot 2016-03-12 at 3 59 30 pm" src="https://cloud.githubusercontent.com/assets/4008351/13725334/6d7fd7b8-e86c-11e5-8f5e-d9fa955da05e.png">

**Comment by lixun910** [comment]
Please verify in 1.8.11

**Comment by lanselin** [comment]
still seems to be a problem (using 1.8.11)

**Comment by lanselin** [comment]
actually, the fix is incorrect. now the tick marks in the histogram in the category editor are incorrect. they are now the same as in the regular histogram. see picture above, those are the correct tick marks for the histogram in the category editor. however, when applying this custom category to the regular histogram, the tick marks are incorrect (on the histogram). now we have the problem in both the category editor and in the histogram. the correct solution is to have the tick marks from the category editor histogram - shown above in my first post - to apply to the regular histogram. so they should be 4, 8, 12.
attached is the current category editor histogram for the same example. note how the tick marks are 6.1, 8.89 and 11.7, not 4, 8, 12 as above

<img width="714" alt="screen shot 2016-03-13 at 8 17 51 am" src="https://cloud.githubusercontent.com/assets/4008351/13728609/941788c0-e8f4-11e5-890c-a7210a0b6693.png">

**Comment by lixun910** [comment]
My misunderstood on the request. Now the proposed fix is Histogram will applies the same cut-off as in Category Editor.

Please verify in 1.8.13

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.8.13 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).

<img width="1319" alt="screen shot 2016-03-13 at 6 23 23 pm" src="https://cloud.githubusercontent.com/assets/13679743/13732912/ba16ddc4-e948-11e5-9657-3d2a672176a9.png">
