### ISSUE TITLE
Scatterplot status bar: Don't show select rect

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#372]
Let's remove the "select rect" from the status bar of the scatter plot and bubble chart since we can't make sense of the numbers (e.g. in image below there are negatives but the min value for that variable is positive):

![image](https://cloud.githubusercontent.com/assets/13679743/13727640/7c7820f4-e8b7-11e5-9b6b-12da24fcb9ee.png)

The relevant code for this might be here:

void ScatterNewPlotCanvas::UpdateStatusBar()
{
	wxStatusBar* sb = template_frame->GetStatusBar();
	if (!sb) return;
	wxString s;
    if (highlight_state->GetTotalHighlighted()> 0) {
		s << "#selected=" << highlight_state->GetTotalHighlighted();
        
		if (brushtype == rectangle) {
			wxRealPoint pt1 = MousePntToObsPnt(sel1);
			wxRealPoint pt2 = MousePntToObsPnt(sel2);
			wxString xmin = GenUtils::DblToStr(GenUtils::min<double>(pt1.x,
																	 pt2.x));
			wxString xmax = GenUtils::DblToStr(GenUtils::max<double>(pt1.x,
																	 pt2.x));
			wxString ymin = GenUtils::DblToStr(GenUtils::min<double>(pt1.y,
																	 pt2.y));
			wxString ymax = GenUtils::DblToStr(GenUtils::max<double>(pt1.y,
																	 pt2.y));
			s << ", select rect: ";
			s << GetNameWithTime(0) << "=[" << xmin << "," << xmax << "] and ";
			s << GetNameWithTime(1) << "=[" << ymin << "," << ymax << "]";
		}

**Comment by lixun910** [comment]
Please verify in 1.8.13

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.8.13.
