### ISSUE TITLE
conditional plot: histogram labels are incorrect

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#373]
the labels for the histogram in the conditional plot seem to be incorrect. see attached figure. the conditioning variables are POVINDEX and PCINC and the histogram is supposed to be for MALKIDS. however, the histograms all have POVINDEX as their label, whereas it should be MALKIDS. in 1.8.11.

<img width="696" alt="screen shot 2016-03-13 at 8 48 20 am" src="https://cloud.githubusercontent.com/assets/4008351/13728771/ddcd9aa0-e8f8-11e5-9d2e-e688f26cc75c.png">

**Comment by lixun910** [comment]
Please verify it in 1.8.13

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.8.13 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
