### ISSUE TITLE
moran scatterplot toolbar tooltip

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#374]
tooltip is Moran Scatter Plots, should be singular, Moran Scatter Plot

**Comment by lixun910** [comment]
Please verify it in 1.8.13

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.8.13 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).

Moran I Scatter Plot --> Moran Scatter Plot

**Comment by lixun910** [comment]
Please verify in 1.8.15

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.97.
