### ISSUE TITLE
time editor dialog: no way to remove incorrect number of time periods

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#376]
when the number of time periods is (accidentally) set to an incorrect number, for example when highlighting one too many variables in the left hand column and moving them to the middle column, the number of time periods (not their labels) seems to be hard coded. for example, after moving nine variables to the middle, the number of time periods is set to 9 and cannot be changed. their labels can be edited, but there doesn't seem to be a way to remove the time periods. similarly, after closing and re-opening the time editor, the number of time periods is fixed.

there should be a way to clear the time periods in the "Time" column.
<img width="751" alt="screen shot 2016-03-13 at 1 49 01 pm" src="https://cloud.githubusercontent.com/assets/4008351/13730342/cbe099b2-e922-11e5-8969-826c8530def9.png">

**Comment by lixun910** [comment]
Right click, there should be a popup menu with “Remove Time” item.

**Comment by lanselin** [comment]
right click does not work.
note: this is when i start the time editor, there are no grouped variables, but the 9 time periods show
up as time 0 to time 8 in the Time column.

**Comment by jkoschinsky** [comment]
Did you try double-right clicking?

**Comment by lanselin** [comment]
yes. it must have to do with the particular sequence of operations i did.
i will try to re-create. right click works on an empty dialog.

**Comment by lanselin** [comment]
ok, i got it again. it seems to happen after i move all the grouped variables back to the
left-most column. the time periods are still there. then i close the time editor and re-open.
the same time periods are in the “Time” column (no variables under Name) and the
right click option does not work.

**Comment by lixun910** [comment]
In the code, there is only one condition that prevents the right-click popup-menu: when you
are editing the time label, you can’t right-click to show pop-up menu. This is limited by the wxWidgets.

This fix will set by default “editing” flag to false to solve this issue (potentially). So still need your verification.

Please verify it in 1.8.13

**Comment by jkoschinsky** [comment]
GeoDa 1.8.13 (Win 7 Professional (64-bit)).
Nat.shp

Steps:
1. Group HR60-90 (from left to middle column)
2. Move variables from middle to right
3. Move group back from right to middle and left

Right-click on time periods to "remove time." This works in Mac OSX with single right-click but in Windows it still requires double right-click for some reason.

**Comment by lixun910** [comment]
Please verify in 1.8.15

**Comment by jkoschinsky** [comment]
GeoDa 1.7.99.
Works in OSX Yosemite, 10.10.5 but not yet in Win 7 Professional (64-bit): In Win, Add Time is active but Remove Time is greyed out.

Steps:
1. Group HR60-90 (from left to middle column)
2. Move variables from middle to right
3. Move group back from right to middle and left
4. Right-click on time labels

**Comment by jkoschinsky** [comment]
Just confirmed this works in Windows as well if you first select the time period you want to remove.

**Comment by lixun910** [comment]
The right-click on wxListCtrl behaves different on Windows vs. OSX.
This fix is to make the right-click behaves the same on both Win/Mac
pop-up the menu. But one has to select an item to enable the “Delete
Time” menu-item.

**Comment by lixun910** [comment]
Please verify in 1.7.103

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.103 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
