### ISSUE TITLE
Shorten precision threshold message

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#378]
Current message:

![image](https://cloud.githubusercontent.com/assets/13679743/13732957/52d76d4e-e949-11e5-8c69-3a835c4ad0df.png)

Update to this shorter version:

Set the threshold to bridge the gap between disconnected polygons (often caused by digitizing errors). The value depends on your measurement unit (e.g. 1 foot or 0.0000001 degrees). Use the weights histogram to detect neighborless observations.

**Comment by lixun910** [comment]
Please verify in 1.8.15

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.97.
