### ISSUE TITLE
shift select in time editor

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#379]
there is some strange behavior in shift select in the time editor. here is the example. using natregimes,
one selects say HR60-90 to create a group. then one goes back to the left hand column, the next variable HC60 is highlighted. when shift-click on HC90 then selects all the variables from the beginning to HC90, not HC60-HC90. one needs to click on HC60 first and then H90. the highlight is a bit misleading here, since it doesn't actually mean that HC60 is "active" so to speak.

using 1.8.15

**Comment by lixun910** [comment]
Please verify in 1.7.97

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.99 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
