### ISSUE TITLE
Cluster map bug

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#380]
I was able to replicate the bug Luc found where parts of the map disappears (see top screenshot). Here are my steps. However, when I follow them, I don't get consistently get this bug -- last time it crashed as well (bottom screenshot). If you try a combination of these steps with the log on, may be you can catch it:

1. Load Nepal shapefile
2. create queen weights 
3. create time group
4. open G* (leave defaults checked) with time group
5. save results
6. change randomization and sign. levels about a dozen times
7. open LISA map (defaults checked) with time group
8. save results
9. change randomization and sign levels about a dozen times

if nothing weird happens, try same thing with G map in addition :)

<img width="1200" alt="screen shot 2016-03-15 at 6 53 48 pm" src="https://cloud.githubusercontent.com/assets/13679743/13799850/86ab1934-eae0-11e5-911e-0c2330f5bdb6.png">

<img width="192" alt="screen shot 2016-03-15 at 7 03 20 pm" src="https://cloud.githubusercontent.com/assets/13679743/13799868/9f59a5d6-eae0-11e5-99be-95f1bcda8f3e.png">

**Comment by lanselin** [comment]
the commonality with when I got the bug is that I also changed randomization
and significance levels several times.

**Comment by lixun910** [comment]
Please verify in 1.7.97

**Comment by jkoschinsky** [comment]
opened a dozen different cluster maps and changed their significance level and number of permutations without getting the same bug. Closing for now.
