### ISSUE TITLE
Redesign Averages Chart Interface

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#381]
Several people have found it difficult to navigate the averages chart interface and found the output too complex/confusing (especially for the regimes+ time option). Here is a mockup for a proposed redesign of the interface that Luc and I discussed today (see link to PDF below mockup for more details). We can skype about the details if anything is unclear.

The idea is to use a dialog similar to that for the correlogram, which remains open after the view is generated so people can change the parameters on the fly.

<img width="435" alt="screen shot 2016-03-16 at 7 14 18 pm" src="https://cloud.githubusercontent.com/assets/13679743/13834314/574ac704-ebab-11e5-9036-196d72163bbe.png">

[avg chart dialog.pdf](https://github.com/lixun910/geoda/files/177156/avg.chart.dialog.pdf)

**Comment by lixun910** [comment]
Please verify in 1.7.99

**Comment by jkoschinsky** [comment]
Feedback on the new interface has been really positive.

One question: For selected at time 0-1, "excluded" and "all" are also highlighted in the graph, which I think is confusing. Is it possible to only highlight selected?

<img width="1382" alt="screen shot 2016-03-24 at 11 15 18 am" src="https://cloud.githubusercontent.com/assets/13679743/14026835/f134ebe0-f1b1-11e5-8ce6-4f4e41aba417.png">

Same with excluded:

<img width="1382" alt="screen shot 2016-03-24 at 11 14 08 am" src="https://cloud.githubusercontent.com/assets/13679743/14026841/f9bc97cc-f1b1-11e5-82b1-276727877a1e.png">

**Comment by jkoschinsky** [comment]
Can you add the variable name back in the header of the view? 
Right now it only says: Averages Comparison Chart (see correlogram and other views)

**Comment by lixun910** [comment]
Please verify in 1.7.101

**Comment by jkoschinsky** [comment]
It looks like the fix only displays selected or excluded trends if either are chosen for different time periods, which works, too. For this case (selected-excluded, same time), all is also highlighted in yellow. Is there a way to only yellow-highlight selected and excluded but not all?

<img width="1304" alt="screen shot 2016-03-28 at 5 56 41 pm" src="https://cloud.githubusercontent.com/assets/13679743/14094825/ca717202-f50e-11e5-982c-32eef8f09d6b.png">

**Comment by lixun910** [comment]
Sure, I leave it as a reference line on purpose. I will fix this in next build.

**Comment by lixun910** [comment]
Please verify in 1.7.103

remove average line;
update “Apply” button to “Run Diff-in-Diff Test”;
remove checkbox “Run Diff-in-Diff Test”;
update some warning messages;
update “Save Dummy” functions;

**Comment by jkoschinsky** [comment]
Luc: It seems that the bar for the overall mean is missing in the graph (see below). This used to be a horizontal line in black.

Julia: I think we lost this in response to one of the comments in ticket 381 re. only using the yellow highlight for e.g. selected, instead of highlighting selected, unselected and all for selected. Ideally, we'd put the overall mean back in and still only highlight what is selected instead of all three.

Luc: The overall mean should definitely be in, it gives perspective to the other values.

**Comment by jkoschinsky** [comment]
Looks like the overall mean is still missing?

![Uploading Screen Shot 2016-04-07 at 5.10.57 AM.png…]()

**Comment by lanselin** [comment]
in a pure cross-sectional setup, it is there (just tested on Cleveland)

**Comment by jkoschinsky** [comment]
The problem might be related to not having made a selection in one of the views but choosing selected vs. excluded in the averages chart. In that case GeoDa treats the overall mean as excluded:

<img width="720" alt="screen shot 2016-04-07 at 5 14 24 am" src="https://cloud.githubusercontent.com/assets/13679743/14350681/a60bd74a-fc7f-11e5-87e8-af90d34d2086.png">

Sometimes you also get a zero line for selected, which wasn't visible in the above view:

<img width="720" alt="screen shot 2016-04-07 at 5 17 04 am" src="https://cloud.githubusercontent.com/assets/13679743/14350757/116a45a8-fc80-11e5-8868-195ba56d0a92.png">

**Comment by lixun910** [comment]
See the vertical axis in the first figure: it’s from [1.8 - 7.4] — that’s why the selected is not shown. Did you change the Y axis range?

**Comment by jkoschinsky** [comment]
no, these were defaults after changing selection

On 7 April 2016 at 10:10, Xun Li <notifications@github.com> wrote:

> See the vertical axis in the first figure: it’s from [1.8 - 7.4] — that’s
> why the selected is not shown. Did you change the Y axis range?
>
>
>
>
> > On Apr 7, 2016, at 5:18 AM, jkoschinsky <notifications@github.com>
> wrote:
> >
> > The problem might be related to not having made a selection in one of
> the views but choosing selected vs. excluded in the averages chart. In that
> case GeoDa treats the overall mean as excluded:
> >
> > <
> https://cloud.githubusercontent.com/assets/13679743/14350681/a60bd74a-fc7f-11e5-87e8-af90d34d2086.png
> >
> > Sometimes you also get a zero line for selected, which wasn't visible in
> the above view:
> >
> > <
> https://cloud.githubusercontent.com/assets/13679743/14350757/116a45a8-fc80-11e5-8868-195ba56d0a92.png
> >
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly or view it on GitHub <
> https://github.com/lixun910/geoda/issues/381#issuecomment-206847225>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/381#issuecomment-206997723>
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by jkoschinsky** [comment]
Let's just put the black line for all back into selected-excluded (and, if possible, only use yellow highlighting for the chosen option, i.e. either selected or excluded instead of the current highlighting of selected, excluded and all). If nothing is selected just have zeros for the obs-mean-sd values and only show the line for all.

**Comment by jkoschinsky** [comment]
When I talk to people about the "Averages Chart" there's some initial confusion about its purpose. 

To clarify this upfront, what do you think about renaming it to the "Difference-In-Means Chart" or to "Difference-in-Means Tests"?

**Comment by lanselin** [comment]
I actually like “averages chart,”  nobody else has it :-)
how about differences chart?
i don’t want it to sound too complicated, four words is
definitely too many.

**Comment by jkoschinsky** [comment]
Then let's keep Averages Chart since people won't otherwise know what the
differences are about :)

On 11 April 2016 at 09:46, Luc Anselin <notifications@github.com> wrote:

> I actually like “averages chart,” nobody else has it :-)
> how about differences chart?
> i don’t want it to sound too complicated, four words is
> definitely too many.
>
>
> > On Apr 11, 2016, at 11:38 AM, jkoschinsky <notifications@github.com>
> wrote:
> >
> > When I talk to people about the "Averages Chart" there's some initial
> confusion about its purpose.
> >
> > To clarify this upfront, what do you think about renaming it to the
> "Difference-In-Means Chart" or to "Difference-in-Means Tests"?
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub <
> https://github.com/lixun910/geoda/issues/381#issuecomment-208406598>
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/381#issuecomment-208443621>
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.103 (OSX Yosemite, 10.10.5)

Steps:
1. Choose time grouped variable
2. make selection on map

Result:
<img width="862" alt="screen shot 2016-04-13 at 5 14 33 am" src="https://cloud.githubusercontent.com/assets/13679743/14492829/bfce8658-0136-11e6-8427-c176f756da23.png">

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.109 (OSX Yosemite, 10.10.5)
Data: Test Data.zip (same as before

Steps:
1. Choose time grouped variable (BnkAll time 0-time16)
2. Make selection on map

Problem persists:
<img width="1329" alt="screen shot 2016-04-13 at 12 26 44 pm" src="https://cloud.githubusercontent.com/assets/13679743/14506558/34da38f2-0173-11e6-9c9c-3c6a4c7244ba.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.7.109 (OSX Yosemite, 10.10.5)

Steps:

1. open time-grouped variable with select/unselect but no selection: red zero line is displayed (right)
2. if you make a selection and then unselect, the Y-axis is truncated above zero, so you don’t see the red zero line (left)

<img width="1445" alt="screen shot 2016-04-14 at 5 42 05 am" src="https://cloud.githubusercontent.com/assets/13679743/14528825/56595632-0206-11e6-938d-decb7c575045.png">

Since the red zero line might be confusing, why don’t we set the default for 1 to that of 2 or to some value above 0. I played with this using 0.1 and 0.2 but in this case the red zero line shifts below the x-axis instead of not being displayed:

<img width="716" alt="screen shot 2016-04-14 at 5 42 51 am" src="https://cloud.githubusercontent.com/assets/13679743/14528845/7471b560-0206-11e6-9fdf-301accb30cdd.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.7.109 (OSX Yosemite, 10.10.5)

It looks like in the process of dealing with the highlighting issue, we lost the trend line that connects the averages for each time period (or may be we never had it). Let's add this back in (same as black line for selected/unselected) and leave the highlighting in brown and purple as it is now.

<img width="1356" alt="screen shot 2016-04-14 at 8 19 36 am" src="https://cloud.githubusercontent.com/assets/13679743/14533615/9d96f3d8-021a-11e6-8e60-87642e685f53.png">

**Comment by jkoschinsky** [comment]
The time/all problem is fixed and the Y-axis drop below X, too. 

Now the only remaining problem is still related to the Adjust Value Range of Y-axis right-click option:
For instance, in the example below, if I want to adjust the Y-axis to 2.1 should be able to do this but am no longer able to do this and asked to specify a Y value of zero or below:

<img width="1297" alt="screen shot 2016-04-15 at 3 18 43 am" src="https://cloud.githubusercontent.com/assets/13679743/14558736/f312ad40-02b8-11e6-9fee-dfa2c88f4544.png">

The other thing is that after you edit the Y-axis, if you click on it again, instead of giving you the view to edit the Y values, it jumps back to the default setting.

**Comment by jkoschinsky** [comment]
User can now specify Y axis range that's narrower than the value range but that's easy to recognize and fix since you don't see anything. Closing for now.
