### ISSUE TITLE
Table merge error message

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#383]
Here's a small issue I ran into yesterday before the logged version of GeoDa was available. I just tried to replicate the problem with the log but now it runs fine, so just FYI in case you have a sense of what is going on.

I merged the attached (no missing data DBF) file with the shapefile's dbf using the CODE field. When I tried to save the table, I got this error message:

<img width="419" alt="dbf error merge" src="https://cloud.githubusercontent.com/assets/13679743/13861912/27f44866-ec4d-11e5-99f8-dd5b191baf6b.png">

Then I went to save as new shapefile and it saved the merged table without problem. So I'm not sure why the flag was triggered that there's something wrong with the dbf format. One question is if the problem is really independent of the DBF format and pointing to something else?

Let's also update the text of the error message to:

This DBF format is not supported by GeoDa.

[table merge.zip](https://github.com/lixun910/geoda/files/178733/table.merge.zip)

**Comment by lixun910** [comment]
Please verify in 1.7.99

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.99 (OSX Yosemite, 10.10.5). Don't get error anymore with same steps.
