### ISSUE TITLE
Correlogram line disappears

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#384]
GeoDa 1.7.99 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
Nat.shp

The correlogram line disappears with the following specification in Windows (it goes in an out if you keep selecting apply):

![correlogram](https://cloud.githubusercontent.com/assets/13679743/14029478/9191b8ea-f1bf-11e5-8685-55b18fa684c6.png)

On the Mac side, the line is also drawn in some funny ways:

<img width="870" alt="screen shot 2016-03-24 at 12 56 38 pm" src="https://cloud.githubusercontent.com/assets/13679743/14029597/3af22334-f1c0-11e5-88dc-2f8d366a4eda.png">

**Comment by lixun910** [comment]
This happens due to an insufficient random sampling: the iterations number is not enough to get enough samples in some bins, and lead to NaN autocorrelation value. 

The proposed solution is popup a warning message to tell people "insufficient random sampling" and "change the iteration value".  

Let me know if you want any updates of this fix. Thanks!

![screen shot 2016-03-24 at 11 23 56 pm](https://cloud.githubusercontent.com/assets/2423887/14039246/822de948-f217-11e5-8beb-28c2f306400b.png)

**Comment by jkoschinsky** [comment]
how about:

The sample size for random sampling is too small. Please increase the
number of iterations.

On 24 March 2016 at 23:25, Xun Li <notifications@github.com> wrote:

> This happens due to an insufficient random sampling: the iterations number
> is not enough to get enough samples in some bins, and lead to NaN
> autocorrelation value.
>
> The proposed solution is popup a warning message to tell people
> "insufficient random sampling" and "change the iteration value".
>
> Let me know if you want any updates of this fix. Thanks!
>
> [image: screen shot 2016-03-24 at 11 23 56 pm]
> <https://cloud.githubusercontent.com/assets/2423887/14039246/822de948-f217-11e5-8beb-28c2f306400b.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/384#issuecomment-201162299>
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by jkoschinsky** [comment]
also let's update this:

<img width="420" alt="screen shot 2016-03-24 at 11 34 24 pm" src="https://cloud.githubusercontent.com/assets/13679743/14039400/0c3bc87a-f219-11e5-871e-f9bb8a094066.png">

to this:

Please select another variable with values more suitable for computing a correlogram.

**Comment by lixun910** [comment]
Please verify in 1.7.101

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.101 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
