### ISSUE TITLE
variable name edits not saved when export (save as) dbf

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#385]
Here's the scenario: a csv file is loaded and then File > Save As is selected to export to a dbf format. The  interface flags the variable names that are more than 10 digits long and suggests alternative variable names. When the latter are edited and the file is saved (OK), the variable names in the dbf file are the ones suggested by GeoDa, not the edited ones. So somehow the edits are not recorded.
Using 1.7.101.

**Comment by lixun910** [comment]
Thanks for reporting this bug. The proposed fix will be in 1.7.103

**Comment by lixun910** [comment]
Please verify in 1.7.103

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.103
