### ISSUE TITLE
save automatically creates project file

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#386]
after making some changes to a table (e.g., editing a variable name) and using Save (either the toolbar button or the File > Save command), a project file is automatically created, even when none exists. is that the desired behavior? I would suggest not creating a project file when none currently exists, and only creating it when there already is one. This is "save" of a "current" state, so why create new files.

**Comment by lanselin** [comment]
forgot to specify using 1.7.101

**Comment by jkoschinsky** [comment]
did you have weights specified?

On 1 April 2016 at 07:45, Luc Anselin <notifications@github.com> wrote:

> forgot to specify using 1.7.101
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/386#issuecomment-204423499>
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by lanselin** [comment]
no weights, only operation was to convert a csv file (non-spatial) to a dbf file and edit
the variable names that were too long for dbf.

**Comment by jkoschinsky** [comment]
I agree, I think it makes sense to automatically save the project file when
time groups are specified (and possibly weights) so those specifications
aren't inadvertently lost but not otherwise.

On 1 April 2016 at 07:50, Luc Anselin <notifications@github.com> wrote:

> no weights, only operation was to convert a csv file (non-spatial) to a
> dbf file and edit
> the variable names that were too long for dbf.
>
>
> > On Apr 1, 2016, at 9:49 AM, jkoschinsky <notifications@github.com>
> wrote:
> >
> > did you have weights specified?
> >
> > On 1 April 2016 at 07:45, Luc Anselin <notifications@github.com> wrote:
> >
> > > forgot to specify using 1.7.101
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/lixun910/geoda/issues/386#issuecomment-204423499>
> > >
> >
> >
> >
> > --
> > ************************
> > Julia Koschinsky, Ph.D.
> > Research Director
> > Associate Research Professor
> > Arizona State University
> > School of Geographical Sciences and Urban Planning
> > GeoDa Center for Geospatial Analysis and Computation
> > julia.koschinsky@asu.edu
> >
> > http://geodacenter.asu.edu
> > http://www.facebook.com/geodacenter
> > http://twitter.com/GeoDaCenter
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub <
> https://github.com/lixun910/geoda/issues/386#issuecomment-204424892>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/386#issuecomment-204425412>
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by lixun910** [comment]
Please verify in 1.7.103

**Comment by jkoschinsky** [comment]
1.7.103

Right now when you specify time or weights and save/close, the project file isn't added, so you would lose the time groupings and loaded weights. For those two cases (having time groupings or weights), can we automatically add a project file so these specs aren't lost?

**Comment by lanselin** [comment]
i have also had some instances where the weights information was not saved into the project
file when closing the project, but i cannot replicate right now.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.103 (OSX Yosemite, 10.10.5

Confirmed that .gda file is now saved with either weights or time grouped variables.
