### ISSUE TITLE
nokia basemap is slow

### ISSUE THREAD

**Issue by lixun910** [lixun910/geoda#388]
Using the nokia day base map and it takes a very long time to update
when zooming in — to the point that the “casual user” might think it
doesn’t work, something like 15 seconds in the cleveland example i am
working on.

**Comment by lixun910** [comment]
Will fix it. Here is the feedback from NOKIA HERE:

I think the issue maybe that you making calls to the CIT (Customer Integration Testing) Environment instead of to the production APIs. These types of calls include “.cit” in their URL, examples include:
-          http://route.cit.api.here.com

-          https://traffic.maps.cit.here.com

-          https://geocoder.cit.api.here.com

 
Our URLs should look like this instead:
-          http://route.api.here.com

-          https://traffic.maps.here.com

-          https://geocoder.api.here.com

**Comment by lixun910** [comment]
Change to a progressive tile rendering solution. Needs testing and verification.
<img width="1440" alt="screen shot 2016-04-05 at 7 13 49 pm" src="https://cloud.githubusercontent.com/assets/2423887/14303847/bef44652-fb62-11e5-8fde-2f2953287658.png">
<img width="1440" alt="screen shot 2016-04-05 at 7 13 55 pm" src="https://cloud.githubusercontent.com/assets/2423887/14303849/c20e09ae-fb62-11e5-9633-0f19626c8c48.png">
<img width="1440" alt="screen shot 2016-04-05 at 7 13 55 pm 1" src="https://cloud.githubusercontent.com/assets/2423887/14303852/c65e656c-fb62-11e5-81ce-07d79c6d1209.png">

**Comment by lixun910** [comment]
Please verify in 1.7.103

**Comment by jkoschinsky** [comment]
It still takes a bit longer but only a few seconds, so I would say it's ok but leaving open in case Luc can test on the original data associated with this ticket.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.103 (OSX Yosemite, 10.10.5).
nat.shp

much faster now!

One thing I noticed is that the brushing on grouped boxplots has a lag on the selection for larger datasets that seems to get worse if I have several (in this case 4) maps with Nokia basemaps open plus a bunch of other views. Not sure if this then becomes a memory issue but wanted to mention it in case this can be fixed.

<img width="450" alt="screen shot 2016-04-07 at 5 26 43 am" src="https://cloud.githubusercontent.com/assets/13679743/14350966/674eaa58-fc81-11e5-9296-dc0c915a50fb.png">

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.103 (OSX Yosemite, 10.10.5).
nat.shp

All Nokia maps load fast with the regular maps. Nokia Hybrid and satellite loads for 10+ seconds on the connectivity maps. This isn't a crucial issue since the main maps are more important but FYI in case it's quick to fix.

**Comment by lixun910** [comment]
Which data did you use? I guess it would be the DEBUG mode causing the slow performance.

Xun

**Comment by jkoschinsky** [comment]
nat.shp

On 7 April 2016 at 10:08, Xun Li <notifications@github.com> wrote:

> Which data did you use? I guess it would be the DEBUG mode causing the
> slow performance.
>
> Xun
>
>
> > On Apr 7, 2016, at 5:30 AM, jkoschinsky <notifications@github.com>
> wrote:
> >
> > Verified in GeoDa 1.7.103 (OSX Yosemite, 10.10.5).
> > nat.shp
> >
> > much faster now!
> >
> > One thing I noticed is that the brushing on grouped boxplots has a lag
> on the selection for larger datasets that seems to get worse if I have
> several (in this case 4) maps with Nokia basemaps open plus a bunch of
> other views. Not sure if this then becomes a memory issue but wanted to
> mention it in case this can be fixed.
> >
> > <
> https://cloud.githubusercontent.com/assets/13679743/14350966/674eaa58-fc81-11e5-9296-dc0c915a50fb.png
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub <
> https://github.com/lixun910/geoda/issues/388#issuecomment-206858287>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/388#issuecomment-206997259>
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.103 (OSX Yosemite, 10.10.5).
