### ISSUE TITLE
Save to GDB bug

### ISSUE THREAD

**Issue by lixun910** [lixun910/geoda#389]
When GDB plugin has not been installed, when user try to save to GDB, the program will crash.

![unnamed](https://cloud.githubusercontent.com/assets/2423887/14300314/8b0a6c0e-fb44-11e5-9cc7-2a189acc8d97.png)

**Comment by lixun910** [comment]
Please verify in 1.7.103

**Comment by jkoschinsky** [comment]
Current: 
The format "FileGDB" is not supported by GeoDa on Mac OSX. 
Note: Please check if related plugin has been installed.

Update:
The format "FileGDB" is not supported by GeoDa on Mac OSX. 
Note: Please check if the related plugin has been installed.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.103 (OSX Yosemite, 10.10.5).
