### ISSUE TITLE
highlight selected in table: column only for dbf

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#392]
when loading a dbf table (no shape file) and selecting observations using the selection tool (e.g., 0 <= var1 <= 10) only the observations in the column of the respective variable are highlighted (e.g., var1 in this example). also, the highlight is blue and not yellow, as in the usual case.

**Comment by lixun910** [comment]
The blue color is for selected column only (e.g. when you click the field name), which is the default behavior of wxwidgets. Can you send a screenshot?
<img width="1043" alt="screen shot 2016-04-12 at 12 01 55 pm" src="https://cloud.githubusercontent.com/assets/2423887/14472107/6f808466-00a6-11e6-8b36-8823d2fbe62a.png">

**Comment by lanselin** [comment]
can’t replicate - ignore. not sure what happened.
