### ISSUE TITLE
save or save as csv creating name field failed

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#395]
here's the use case:
- load a csv table (as a table, no map)
- merge with another csv table
- save, save as and save selected as as a csv all fail with creating
  name field error, for different file names for the output file
- saving as a dbf works fine

<img width="259" alt="screen shot 2016-04-15 at 4 30 33 pm" src="https://cloud.githubusercontent.com/assets/4008351/14574181/f443c4dc-0327-11e6-970a-aad3adc52aa3.png">

**Comment by lanselin** [comment]
apparently a file is created, but it is empty except for a name header

GdaTmp_pricelag_2012q2_2015q4_a.csv

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.7.113 (OSX Yosemite, 10.10.5).

The fix worked in my test case:
<img width="646" alt="screen shot 2016-04-16 at 5 39 21 am" src="https://cloud.githubusercontent.com/assets/13679743/14581005/b1741206-0395-11e6-930a-6e72c05c1264.png">

Leaving ticket open so Luc can confirm for his case.

**Comment by jkoschinsky** [comment]
Luc confirmed as well.
